g-wrap-1.9.7-1-x86_64   * Version bump   * Updated glib2 detection patch for new upstream

diff --git a/source/lib-extra/g-wrap/g-wrap-glib2.patch b/source/lib-extra/g-wrap/g-wrap-glib2.patch
--- a/source/lib-extra/g-wrap/g-wrap-glib2.patch
+++ b/source/lib-extra/g-wrap/g-wrap-glib2.patch
@@ -1,44 +1,81 @@
---- g-wrap-1.9.6/configure.ac.moo	2006-03-27 16:31:41.000000000 -0500
-+++ g-wrap-1.9.6/configure.ac	2006-03-27 16:31:15.000000000 -0500
-@@ -95,7 +95,7 @@
- AM_CONDITIONAL(HAVE_SRFI_35, test "$HAVE_SRFI_35" = yes)
- 
- dnl Check for optional libraries
--PKG_CHECK_MODULES(GLIB, glib, [have_glib=yes], [have_glib=no])
-+PKG_CHECK_MODULES(GLIB, glib-2.0, [have_glib=yes], [have_glib=no])
- AM_CONDITIONAL(HAVE_GLIB, test "$have_glib" = yes)
- 
- dnl Check for compiler flags and warnings. This should be last, since
---- g-wrap-1.9.6/configure.glib2	2006-02-18 15:10:25.000000000 -0500
-+++ g-wrap-1.9.6/configure	2006-02-18 15:11:39.000000000 -0500
-@@ -21699,8 +21699,8 @@
-   if test "x$ac_cv_env_GLIB_CFLAGS_set" = "xset"; then
- 	pkg_cv_GLIB_CFLAGS=$ac_cv_env_GLIB_CFLAGS_value
- elif test -n "$PKG_CONFIG"; then
--	if $PKG_CONFIG --exists "glib" >/dev/null 2>&1; then
--		pkg_cv_GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib" 2>/dev/null`
-+	if $PKG_CONFIG --exists "glib-2.0" >/dev/null 2>&1; then
-+		pkg_cv_GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib-2.0" 2>/dev/null`
- 	else
- 		pkg_failed=yes
- 	fi
-@@ -21718,8 +21718,8 @@
-   if test "x$ac_cv_env_GLIB_LIBS_set" = "xset"; then
- 	pkg_cv_GLIB_LIBS=$ac_cv_env_GLIB_LIBS_value
- elif test -n "$PKG_CONFIG"; then
--	if $PKG_CONFIG --exists "glib" >/dev/null 2>&1; then
--		pkg_cv_GLIB_LIBS=`$PKG_CONFIG --libs "glib" 2>/dev/null`
-+	if $PKG_CONFIG --exists "glib-2.0" >/dev/null 2>&1; then
-+		pkg_cv_GLIB_LIBS=`$PKG_CONFIG --libs "glib-2.0" 2>/dev/null`
- 	else
- 		pkg_failed=yes
- 	fi
-@@ -21731,7 +21731,7 @@
- echo "${ECHO_T}$pkg_cv_GLIB_LIBS" >&6
- 
- if test $pkg_failed = yes; then
--	GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib"`
-+	GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib-2.0"`
+diff -Naur g-wrap-1.9.7.orig/configure g-wrap-1.9.7/configure
+--- g-wrap-1.9.7.orig/configure	2007-01-01 23:35:39.000000000 +0100
++++ g-wrap-1.9.7/configure	2007-01-01 23:38:54.000000000 +0100
+@@ -22859,12 +22859,12 @@
+         pkg_cv_GLIB_CFLAGS="$GLIB_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glib\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "glib") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glib-2.0\"") >&5
++  ($PKG_CONFIG --exists --print-errors "glib-2.0") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib" 2>/dev/null`
++  pkg_cv_GLIB_CFLAGS=`$PKG_CONFIG --cflags "glib-2.0" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -22877,12 +22877,12 @@
+         pkg_cv_GLIB_LIBS="$GLIB_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glib\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "glib") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glib-2.0\"") >&5
++  ($PKG_CONFIG --exists --print-errors "glib-2.0") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_GLIB_LIBS=`$PKG_CONFIG --libs "glib" 2>/dev/null`
++  pkg_cv_GLIB_LIBS=`$PKG_CONFIG --libs "glib-2.0" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -22901,14 +22901,14 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        GLIB_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "glib"`
++	        GLIB_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "glib-2.0"`
+         else
+-	        GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib"`
++	        GLIB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glib-2.0"`
+         fi
  	# Put the nasty error message in config.log where it belongs
- 	echo "$GLIB_PKG_ERRORS" 1>&5
+ 	echo "$GLIB_PKG_ERRORS" >&5
+ 
+-	{ { echo "$as_me:$LINENO: error: Package requirements (glib) were not met:
++	{ { echo "$as_me:$LINENO: error: Package requirements (glib-2.0) were not met:
+ 
+ $GLIB_PKG_ERRORS
+ 
+@@ -22958,10 +22958,10 @@
+ 	GLIB_LIBS=$pkg_cv_GLIB_LIBS
+         { echo "$as_me:$LINENO: result: yes" >&5
+ echo "${ECHO_T}yes" >&6; }
+-	echo building GLib 1.2 support
++	echo building GLib 2.0 support
+ fi
+ else
+-  echo Not building Glib 1.2 support
++  echo Not building Glib 2.0 support
+ fi
+ 
+ 
+diff -Naur g-wrap-1.9.7.orig/configure.ac g-wrap-1.9.7/configure.ac
+--- g-wrap-1.9.7.orig/configure.ac	2007-01-01 23:35:39.000000000 +0100
++++ g-wrap-1.9.7/configure.ac	2007-01-01 23:36:30.000000000 +0100
+@@ -121,9 +121,9 @@
+ dnl Check for optional libraries
+ AC_CHECK_PROG(have_glib, glib-config, yes, no)
+ if test "$have_glib" = yes; then
+-  PKG_CHECK_MODULES(GLIB, glib, [echo building GLib 1.2 support])
++  PKG_CHECK_MODULES(GLIB, glib-2.0, [echo building GLib 2.0 support])
+ else
+-  echo Not building Glib 1.2 support
++  echo Not building Glib 2.0 support
+ fi
+ AM_CONDITIONAL(HAVE_GLIB, test "$have_glib" = yes)
  
