openoffice.org-3.2.1-5-i686
- USE_DEVEL:
  * update to ooo330m4
  * add ecj to makedepends as gcc-gcj no longer depends on it
  * no longer build any language packs
  * always try to build in parallel, then fail back to non-parallel mode
    if necessary

diff --git a/source/xapps/openoffice.org/FrugalBuild b/source/xapps/openoffice.org/FrugalBuild
--- a/source/xapps/openoffice.org/FrugalBuild
+++ b/source/xapps/openoffice.org/FrugalBuild
@@ -16,8 +16,8 @@ else
 	upstream=3.3.0
 	branch=
 	tree=ooo330
-	milestone=2
-	pkgver=$upstream${tree}_m$milestone.14834.gc2258e4
+	milestone=4
+	pkgver=$upstream${tree}_m$milestone.14973.gcee4ef6
 	pkgrel=1
 fi
 pkgdesc="OpenOffice.org, a full office productivity suite."
@@ -31,7 +31,7 @@ depends=('libxml2' 'libart_lgpl' 'libsndfile' 'libgcj-awt>=4.4.0-2' 'nas' 'fontc
 # this is here as gstreamer is only a makedepend
 rodepends=('flac' 'dejavu-ttf')
 # lucene can be any 2.x version actually
-makedepends=('curl>=7.20.0-2' 'intltool' 'tcsh' 'pam-headers' 'gcc-gcj' 'apache-ant' \
+makedepends=('curl>=7.20.0-2' 'intltool' 'tcsh' 'pam-headers' 'gcc-gcj' 'ecj' 'apache-ant' \
 	     'boost' 'icu' 'hunspell' 'imake' 'gccmakedep' 'xalan-j' \
 	     'patch>=2.5.9' 'openclipart' 'xorg-server' 'gstreamer' 'gst-plugins-base' \
 	     'procps' 'openldap' 'gperf' 'xulrunner' 'kdelibs-compiletime' 'libwps' \
@@ -70,12 +70,10 @@ subarchs=('i686 x86_64' 'i686 x86_64' 'i686 x86_64' 'i686 x86_64' 'i686 x86_64')
 subgroups=('kde-extra' 'gnome-extra' 'devel-extra' 'devel-extra' 'xapps')
 subinstall=("" "$_F_gnome_scriptlet" "" "" "")
 
-ooodicts="af cs da de es et fr gl hu it lt ne nl pl pt ru sk sl sr sv sw th vi zu ca he ro"
-ooosubpkgs=('de' 'es' 'fr' 'hu' 'it' 'pt')
-ooosubdescs=('German' 'Spanish' 'French' 'Hungarian' 'Italian' 'Portuguese')
 if ! Fuse $USE_DEVEL; then
-	ooosubpkgs=(${ooosubpkgs[@]} 'af' 'ar' 'be-BY' 'bg' 'bn' 'bn-BD' 'bn-IN' 'br' 'bs' 'ca' 'cy' 'cs' 'da' 'el' 'en-GB' 'en-ZA' 'eo' 'et' 'eu' 'fi' 'ga' 'gl' 'gu-IN' 'he' 'hi-IN' 'hr' 'ja' 'km' 'kn-IN' 'ko' 'lo' 'lt' 'lv' 'mk' 'ms' 'nb' 'ne' 'nl' 'nn' 'nr' 'ns' 'pa-IN' 'pl' 'pt-BR' 'ru' 'rw' 'sh-YU' 'sk' 'sl' 'sr-CS' 'ss' 'st' 'sv' 'sw' 'sw-TZ' 'sx' 'ta-IN' 'th' 'tn' 'tr' 'ts' 've' 'vi' 'xh' 'zh-CN' 'zh-TW' 'zu' 'fa' 'ku' 'as-IN' 'ml-IN' 'mr-IN' 'or-IN' 'te-IN' 'tg' 'ti-ER' 'uk' 'ur-IN' 'dz' 'ka' 'kn' 'sh' 'sr' 'uz' 'by' 'gd' 'gu' 'mn' 'my' 'oc' 'brx' 'dgo' 'kk' 'kok' 'ks' 'mai' 'mni' 'ro' 'sa-IN' 'sat' 'sc' 'sd' 'bo' 'is' 'kid' 'ky' 'om' 'pap' 'ps' 'si' 'ug')
-	ooosubdescs=(${ooosubdescs[@]} 'Afrikaans' 'Arabic' 'Belarusian' 'Bulgarian' 'Bengali' 'Bengali (Bangladesh)' 'Bengali (India)' 'Breton' 'Bosnian' 'Catalan' 'Welsh' 'Czech' 'Danish' 'Greek' 'English (GB)' 'English (South Africa)' 'Esperanto' 'Estonian' 'Basque' 'Finnish' 'Irish' 'Galician' 'Gujarati' 'Hebrew' 'Hindi' 'Croatian' 'Japanese' 'Khmer (Cambodia)' 'Kannada' 'Korean' 'Lao' 'Lithuanian' 'Latvian' 'Macedonian' 'Malay' 'Norwegian Bokmal' 'Nepali' 'Dutch' 'Norwegian Nynorsk' 'Ndebele, South' 'NorthernSotho/Sepedi' 'Punjabi' 'Polish' 'Brazil (Port.)' 'Russian' 'Kinyarwanda' 'Serbian Latin' 'Slovak' 'Slovenian' 'Serbian Cyrillic' 'Swati' 'Sotho' 'Swedish' 'Swahili' 'Swahili ' 'South Georgian' 'Tamil' 'Thai' 'Tswana' 'Turkish' 'Tsonga' 'Venda' 'Vietnamese' 'Xhosa' 'Chinese (simplified)' 'Chinese (traditional)' 'Zulu' 'Persian' 'Kurdish' 'Assamese' 'Malayalam' 'Marathi' 'Oriya' 'Telugu' 'Tajik' 'Tigrinya' 'Ukrainian' 'Urdu' 'Dzongkha' 'Georgian' 'Kannada' 'Serbo-Croatian' 'Serbian' 'Uzbek' 'Belarussian' 'Scottish Gaelic' 'Gujarati' 'Mongolian' 'Malay' 'Occitan' 'Bodo' 'Dogri' 'Kazakh' 'Konkani' 'Kashmiri' 'Maithili' 'Manipuri' 'Romanian' 'Sanskrit' 'Santali' 'Sardinian' 'Sindhi' 'Tibetan' 'Icelandic' 'Kid' 'Ky' 'Afan Oromo' 'Pap' 'Pashto' 'Sinhala' 'Uyghur')
+	ooodicts="af cs da de es et fr gl hu it lt ne nl pl pt ru sk sl sr sv sw th vi zu ca he ro"
+	ooosubpkgs=('de' 'es' 'fr' 'hu' 'it' 'pt' 'af' 'ar' 'be-BY' 'bg' 'bn' 'bn-BD' 'bn-IN' 'br' 'bs' 'ca' 'cy' 'cs' 'da' 'el' 'en-GB' 'en-ZA' 'eo' 'et' 'eu' 'fi' 'ga' 'gl' 'gu-IN' 'he' 'hi-IN' 'hr' 'ja' 'km' 'kn-IN' 'ko' 'lo' 'lt' 'lv' 'mk' 'ms' 'nb' 'ne' 'nl' 'nn' 'nr' 'ns' 'pa-IN' 'pl' 'pt-BR' 'ru' 'rw' 'sh-YU' 'sk' 'sl' 'sr-CS' 'ss' 'st' 'sv' 'sw' 'sw-TZ' 'sx' 'ta-IN' 'th' 'tn' 'tr' 'ts' 've' 'vi' 'xh' 'zh-CN' 'zh-TW' 'zu' 'fa' 'ku' 'as-IN' 'ml-IN' 'mr-IN' 'or-IN' 'te-IN' 'tg' 'ti-ER' 'uk' 'ur-IN' 'dz' 'ka' 'kn' 'sh' 'sr' 'uz' 'by' 'gd' 'gu' 'mn' 'my' 'oc' 'brx' 'dgo' 'kk' 'kok' 'ks' 'mai' 'mni' 'ro' 'sa-IN' 'sat' 'sc' 'sd' 'bo' 'is' 'kid' 'ky' 'om' 'pap' 'ps' 'si' 'ug')
+	ooosubdescs=('German' 'Spanish' 'French' 'Hungarian' 'Italian' 'Portuguese' 'Afrikaans' 'Arabic' 'Belarusian' 'Bulgarian' 'Bengali' 'Bengali (Bangladesh)' 'Bengali (India)' 'Breton' 'Bosnian' 'Catalan' 'Welsh' 'Czech' 'Danish' 'Greek' 'English (GB)' 'English (South Africa)' 'Esperanto' 'Estonian' 'Basque' 'Finnish' 'Irish' 'Galician' 'Gujarati' 'Hebrew' 'Hindi' 'Croatian' 'Japanese' 'Khmer (Cambodia)' 'Kannada' 'Korean' 'Lao' 'Lithuanian' 'Latvian' 'Macedonian' 'Malay' 'Norwegian Bokmal' 'Nepali' 'Dutch' 'Norwegian Nynorsk' 'Ndebele, South' 'NorthernSotho/Sepedi' 'Punjabi' 'Polish' 'Brazil (Port.)' 'Russian' 'Kinyarwanda' 'Serbian Latin' 'Slovak' 'Slovenian' 'Serbian Cyrillic' 'Swati' 'Sotho' 'Swedish' 'Swahili' 'Swahili ' 'South Georgian' 'Tamil' 'Thai' 'Tswana' 'Turkish' 'Tsonga' 'Venda' 'Vietnamese' 'Xhosa' 'Chinese (simplified)' 'Chinese (traditional)' 'Zulu' 'Persian' 'Kurdish' 'Assamese' 'Malayalam' 'Marathi' 'Oriya' 'Telugu' 'Tajik' 'Tigrinya' 'Ukrainian' 'Urdu' 'Dzongkha' 'Georgian' 'Kannada' 'Serbo-Croatian' 'Serbian' 'Uzbek' 'Belarussian' 'Scottish Gaelic' 'Gujarati' 'Mongolian' 'Malay' 'Occitan' 'Bodo' 'Dogri' 'Kazakh' 'Konkani' 'Kashmiri' 'Maithili' 'Manipuri' 'Romanian' 'Sanskrit' 'Santali' 'Sardinian' 'Sindhi' 'Tibetan' 'Icelandic' 'Kid' 'Ky' 'Afan Oromo' 'Pap' 'Pashto' 'Sinhala' 'Uyghur')
 fi
 
 if [ ${#ooosubpkgs[@]} -ne ${#ooosubdescs[@]} ]; then
@@ -183,8 +181,7 @@ build()
 
 	# SMP build
 	if [ ! -z "$MAKEFLAGS" ]; then
-		# Comment this out if you think the build failed because of being SMP.
-		Fuse $USE_DEVEL && Fconfopts="$Fconfopts --with-max-jobs=${MAKEFLAGS/-j}"
+		Fconfopts="$Fconfopts --with-max-jobs=${MAKEFLAGS/-j}"
 		unset MAKEFLAGS
 	fi
 
@@ -215,12 +212,16 @@ build()
 			--with-lucene-core-jar=/usr/share/java/lucene-core.jar \
 			--with-lucene-analyzers-jar=/usr/share/java/lucene-analyzers.jar
 	else
-		Fconf --with-lang="en-US de es fr hu it pt"
+		Fconf --with-git
 	fi
 
 	./download || return 1
 
-	make || return 1
+	# on failure make a stab at rebuilding un-parallel
+	if ! make; then
+		Fsed "^MAX_JOBS=.*" "MAX_JOBS='1'" bin/setup
+		make || return 1
+	fi
 
 	Fmakeinstall
 
@@ -291,22 +292,24 @@ build()
 	Fsplit $pkgname-mono $(grep -v '^%dir' build/mono_list.txt)
 	rm build/mono_list.txt
 
-	# Check for missing language packs.
-	misslangs="`find $Fdestdir -type f |grep registry/res/.*/org|sed 's|.*registry/res/\(.*\)/org.*|\1|'|grep -v en-US |sort -u`"
-	if [ -n "$misslangs" ]; then
-		Fmessage "Unsplitted languages: $misslangs"
-		return 1
-	fi
-
-	# Check for missing dict packs.
 	if ! Fuse $USE_DEVEL; then
-		missdicts="`find $Fdestdir -type f |grep dict-.*oxt |sed 's/.*dict-\(.*\).oxt/\1/'|grep -v en|sort -u`"
-	else
-		missdicts="`find $Fdestdir -type d |grep 'dict-[^/]\+$' |sed 's/.*dict-\(.*\)/\1/'|grep -v en|sort -u`"
-	fi
-	if [ -n "$missdicts" ]; then
-		Fmessage "Unsplitted dicts: $missdicts"
-		return 1
+		# Check for missing language packs.
+		misslangs="`find $Fdestdir -type f |grep registry/res/.*/org|sed 's|.*registry/res/\(.*\)/org.*|\1|'|grep -v en-US|sort -u`"
+		if [ -n "$misslangs" ]; then
+			Fmessage "Unsplitted languages: $misslangs"
+			return 1
+		fi
+
+		# Check for missing dict packs.
+		if ! Fuse $USE_DEVEL; then
+			missdicts="`find $Fdestdir -type f |grep dict-.*oxt |sed 's/.*dict-\(.*\).oxt/\1/'|grep -v en|sort -u`"
+		else
+			missdicts="`find $Fdestdir -type d |grep 'dict-[^/]\+$' |sed 's/.*dict-\(.*\)/\1/'|grep -v en|sort -u`"
+		fi
+		if [ -n "$missdicts" ]; then
+			Fmessage "Unsplitted dicts: $missdicts"
+			return 1
+		fi
 	fi
 
 	# Check for missing subpkgs.
