pacman-2.9.6-20-i686 -optcorrect.diff: slice warnings while using -R or -r and no package needs to be removed also increment pkgrel as i hope we've now fixed all the issues :)

diff --git a/source/base/pacman/pacman-2.9.6-optcorrect.diff b/source/base/pacman/pacman-2.9.6-optcorrect.diff
--- a/source/base/pacman/pacman-2.9.6-optcorrect.diff
+++ b/source/base/pacman/pacman-2.9.6-optcorrect.diff
@@ -57,3 +57,46 @@ diff -Naur pacman-2.9.6.orig/src/pacman.c pacman-2.9.6/src/pacman.c
  	while(optind < argc) {
  		/* add the target to our target array */
  		char *s = strdup(argv[optind]);
+diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
+--- pacman-2.9.6.orig/scripts/makepkg	2005-08-28 19:28:42.000000000 +0200
++++ pacman-2.9.6/scripts/makepkg	2005-08-28 19:33:14.000000000 +0200
+@@ -286,10 +286,12 @@
+ 				removelist="$removelist $i"
+ 			fi
+ 		done
+-		pacman -r $CHROOTDIR -Rc $removelist --noconfirm
+-		if [ "$?" != "0" ]; then
+-			error "Failed to remove packages."
+-			exit 1
++		if [ ! -z "$removelist" ]; then
++			pacman -r $CHROOTDIR -Rc $removelist --noconfirm
++			if [ "$?" != "0" ]; then
++				error "Failed to remove packages."
++				exit 1
++			fi
+ 		fi
+ 	fi
+ }
+@@ -1147,11 +1147,12 @@
+ 	rm -rf src pkg filelist
+ fi
+ 
+-if [ "$RMDEPS" = "1" -a "`id -u`" = "0" -a "$INFAKEROOT" != "1" ]; then
++if [ "$RMDEPS" = "1" -a \( ! -z "$deplist" -o ! -z "$makedeplist" \) ]; then
++if [ "`id -u`" = "0" -a "$INFAKEROOT" != "1" ]; then
+ 	msg "Removing installed dependencies..."
+ 	pacman -R $makedeplist $deplist
+ 
+-elif [ "$RMDEPS" = "1" -a "$DEP_SUDO" = "1" ]; then
++elif [ "$DEP_SUDO" = "1" ]; then
+ 	msg "Removing installed dependencies..."
+ 	if [ "$INFAKEROOT" = "1" ]; then
+ 		FAKEROOTKEY2=$FAKEROOTKEY
+@@ -1163,6 +1164,7 @@
+ 		unset FAKEROOTKEY2
+ 	fi
+ fi
++fi
+ 
+ # check optimalization and write it to $BUILDSCRIPT
+ msg "Checking for optimalization..."
