pacman-2.9.6-10-i686 -lastmod.diff: new option: -L to disable updating of the "Last modified" line -chkdep.diff: ported to the new -lastmod.diff -up2date.diff: now "Passed" or "FAILED" is printed to stderr,  makepkg -g >>FrugalBuild works again  ported to the new -lastmod.diff -pacman_source.diff: ported to the new -lastmod.diff -optimalization_and_logging.diff: ported to the new -lastmod.diff -sha1.diff: now a warning is printed if no md5sums() nor sha1sums() are  defined  -g and -G are replaced: -g generates sha1sums  ported to the new -lastmod.diff md5sums() -> sha1sums() -nocache.diff: new option: -B to disable ccache -sbu.diff: now makepkg estimates the build time (in hours, seconds, minutes)

diff --git a/source/base/pacman/pacman-2.9.6-sha1.diff b/source/base/pacman/pacman-2.9.6-sha1.diff
--- a/source/base/pacman/pacman-2.9.6-sha1.diff
+++ b/source/base/pacman/pacman-2.9.6-sha1.diff
@@ -7,8 +7,8 @@ Description: Adds support for sha1 hash arrays to makepkg.
  scripts/makepkg  |   75 +++++++++++++++++++++++++++++++++++++++++++++++++------
  2 files changed, 81 insertions(+), 8 deletions(-)
 diff -Naur pacman-2.9.6.orig/doc/makepkg.8.in pacman-2.9.6/doc/makepkg.8.in
---- pacman-2.9.6.orig/doc/makepkg.8.in	2005-07-20 23:43:00.000000000 +0200
-+++ pacman-2.9.6/doc/makepkg.8.in	2005-07-20 23:49:04.000000000 +0200
+--- pacman-2.9.6.orig/doc/makepkg.8.in	2005-08-02 21:07:13.000000000 +0200
++++ pacman-2.9.6/doc/makepkg.8.in	2005-08-02 21:07:27.000000000 +0200
 @@ -289,6 +289,15 @@
  \fImd5sums\fP line from the bottom to an appropriate location.
  
@@ -38,46 +38,50 @@ diff -Naur pacman-2.9.6.orig/doc/makepkg.8.in pacman-2.9.6/doc/makepkg.8.in
  Output syntax and commandline options.
  .TP
 diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
---- pacman-2.9.6.orig/scripts/makepkg	2005-07-20 23:43:00.000000000 +0200
-+++ pacman-2.9.6/scripts/makepkg	2005-07-20 23:47:00.000000000 +0200
-@@ -195,6 +195,7 @@
+--- pacman-2.9.6.orig/scripts/makepkg	2005-08-02 21:07:13.000000000 +0200
++++ pacman-2.9.6/scripts/makepkg	2005-08-02 21:09:01.000000000 +0200
+@@ -194,7 +194,8 @@
+ 	echo "  -d, --nodeps     Skip all dependency checks"
  	echo "  -e, --noextract  Do not extract source files (use existing src/ dir)"
  	echo "  -f, --force      Overwrite existing package"
- 	echo "  -g, --genmd5     Generate MD5sums for source files"
-+	echo "  -G, --gensha1    Generate SHA1sums for source files"
+-	echo "  -g, --genmd5     Generate MD5sums for source files"
++	echo "  -g, --gensha1    Generate SHA1sums for source files"
++	echo "  -G, --genmd5     Generate MD5sums for source files"
  	echo "  -h, --help       This help"
  	echo "  -i, --install    Install package after successful build"
  	echo "  -j <jobs>        Set MAKEFLAGS to \"-j<jobs>\" before building"
-@@ -222,6 +223,7 @@
+@@ -221,6 +222,7 @@
  INSTALL=0
  DOWNLOAD=""
- GENMD5=0
+ NOLASTMOD=0
 +GENSHA1=0
+ GENMD5=0
  DEP_BIN=0
  DEP_SUDO=0
- DEP_SRC=0
-@@ -253,6 +255,7 @@
+@@ -252,6 +254,7 @@
+ 		--nostrip)    NOSTRIP=1 ;;
  		--nobuild)    NOBUILD=1 ;;
  		--nocolor)    USE_COLOR="n" ;;
- 		--genmd5)     GENMD5=1 ;;
 +		--gensha1)    GENSHA1=1 ;;
+ 		--genmd5)     GENMD5=1 ;;
  		--rmdeps)     RMDEPS=1 ;;
  		--noup2date)     NOUP2DATE=1 ;;
- 		--logging)    LOGGING=1 ;;
 @@ -265,7 +268,7 @@
  			exit 1
  			;;
  		-*)
--			while getopts "acCsSbdehifgj:l:kmnorp:uw:-" opt; do
-+			while getopts "acCsSbdehifgGj:l:kmnorp:uw:-" opt; do
+-			while getopts "acCsSbdehifgj:l:Lkmnorp:uw:-" opt; do
++			while getopts "acCsSbdehifgGj:l:Lkmnorp:uw:-" opt; do
  				case $opt in
  					a) SEARCHDEPS=1 ;;
  					c) CLEANUP=1 ;;
-@@ -275,6 +278,7 @@
+@@ -274,7 +277,8 @@
+ 					d) NODEPS=1 ;;
  					e) NOEXTRACT=1 ;;
  					f) FORCE=1 ;;
- 					g) GENMD5=1 ;;
-+					G) GENSHA1=1 ;;
+-					g) GENMD5=1 ;;
++					g) GENSHA1=1 ;;
++					G) GENMD5=1 ;;
  					h)
  						usage
  						exit 0
@@ -90,7 +94,7 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
  	if [ "$INSTALL" = "1" ]; then
  		warning "a package has already been built, installing existing package."
  		pacman --upgrade $PKGDEST/${pkgname}-${pkgver}-${pkgrel}-${CARCH}.fpm
-@@ -524,16 +528,13 @@
+@@ -524,38 +528,66 @@
  	fi
  done
  
@@ -100,54 +104,89 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
  		warning "Skipping source extraction       -- using existing src/ tree"
  		warning "Skipping source integrity checks -- using existing src/ tree"
  	else
++		# SHA1 validation
++		if [ ${#sha1sums[@]} -eq ${#source[@]} ]; then
++			if [ `type -p sha1sum` ]; then
++				msg "Validating source files with SHA1sums"
++				errors=0
++				idx=0
++				for netfile in ${source[@]}; do
++					file=`strip_url $netfile`
++					echo -n "    $file ... " >&2
++					echo "${sha1sums[$idx]}  $file" | sha1sum -c - >/dev/null 2>&1
++					if [ $? -ne 0 ]; then
++						echo "FAILED" >&2
++						errors=1
++					else
++						echo "Passed" >&2
++					fi	
++					idx=$(($idx+1))
++				done
++				if [ $errors -gt 0 ]; then
++					error "One or more files did not pass the validity check!"
++					exit 1
++				fi
++			else
++				warning "The sha1sum program is missing.  Cannot verify source files!"
++				sleep 1
++			fi
  		# MD5 validation
 -		if [ ${#md5sums[@]} -ne ${#source[@]} ]; then
 -			warning "MD5sums are missing or incomplete.  Cannot verify source integrity."
 -			#sleep 1
 -		elif [ `type -p md5sum` ]; then
-+		if [ ${#md5sums[@]} -eq ${#source[@]} -a `type -p md5sum` ]; then
- 			msg "Validating source files with MD5sums"
- 			errors=0
- 			idx=0
-@@ -553,10 +554,36 @@
- 				error "One or more files did not pass the validity check!"
- 				exit 1
+-			msg "Validating source files with MD5sums"
+-			errors=0
+-			idx=0
+-			for netfile in ${source[@]}; do
+-				file=`strip_url $netfile`
+-				echo -n "    $file ... " >&2
+-				echo "${md5sums[$idx]}  $file" | md5sum -c - >/dev/null 2>&1
+-				if [ $? -ne 0 ]; then
+-					echo "FAILED" >&2
+-					errors=1
+-				else
+-					echo "Passed" >&2
+-				fi	
+-				idx=$(($idx+1))
+-			done
+-			if [ $errors -gt 0 ]; then
+-				error "One or more files did not pass the validity check!"
+-				exit 1
++		elif [ ${#md5sums[@]} -eq ${#source[@]} ]; then
++			if [ `type -p md5sum` ]; then
++				msg "Validating source files with MD5sums"
++				errors=0
++				idx=0
++				for netfile in ${source[@]}; do
++					file=`strip_url $netfile`
++					echo -n "    $file ... " >&2
++					echo "${md5sums[$idx]}  $file" | md5sum -c - >/dev/null 2>&1
++					if [ $? -ne 0 ]; then
++						echo "FAILED" >&2
++						errors=1
++					else
++						echo "Passed" >&2
++					fi	
++					idx=$(($idx+1))
++				done
++				if [ $errors -gt 0 ]; then
++					error "One or more files did not pass the validity check!"
++					exit 1
++				fi
++			else
++				warning "The md5sum program is missing.  Cannot verify source files!"
++				sleep 1
  			fi
--		else
-+		elif [ ! `type -p md5sum` ]; then
- 			warning "The md5sum program is missing.  Cannot verify source files!"
- 			sleep 1
- 		fi
 +		
-+		# SHA1 validation
-+		if [ ${#sha1sums[@]} -eq ${#source[@]} -a `type -p sha1sum` ]; then
-+			msg "Validating source files with SHA1sums"
-+			errors=0
-+			idx=0
-+			for netfile in ${source[@]}; do
-+				file=`strip_url $netfile`
-+				echo -n "    $file ... " >&2
-+				echo "${sha1sums[$idx]}  $file" | sha1sum -c - >/dev/null 2>&1
-+				if [ $? -ne 0 ]; then
-+					echo "FAILED" >&2
-+					errors=1
-+				else
-+					echo "Passed" >&2
-+				fi	
-+				idx=$(($idx+1))
-+			done
-+			if [ $errors -gt 0 ]; then
-+				error "One or more files did not pass the validity check!"
-+				exit 1
-+			fi
-+		elif [ ! `type -p sha1sum` ]; then
-+			warning "The sha1sum program is missing.  Cannot verify source files!"
-+			sleep 1
-+		fi
+ 		else
+-			warning "The md5sum program is missing.  Cannot verify source files!"
+-			sleep 1
++			warning "MD5sums and SHA1sums are missing or incomplete.  Cannot verify source integrity."
+ 		fi
  		# extract sources
  		msg "Extracting Sources..."
- 		for netfile in ${source[@]}; do
-@@ -594,6 +621,7 @@
+@@ -594,6 +626,7 @@
  	fi
  else
  # generate md5 hashes
@@ -155,7 +194,7 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
  	if [ ! `type -p md5sum` ]; then
  		error "Cannot find the md5sum program."
  		exit 1
-@@ -629,6 +657,37 @@
+@@ -629,6 +662,37 @@
  	done
  	plain ""
  	exit 0
