pacman-2.9.5-9-i686 quick fix: 4 new modification in -arch.diff

diff --git a/source/base/pacman/pacman-2.9.5-arch.diff b/source/base/pacman/pacman-2.9.5-arch.diff
--- a/source/base/pacman/pacman-2.9.5-arch.diff
+++ b/source/base/pacman/pacman-2.9.5-arch.diff
@@ -58,6 +58,19 @@ diff -Naur pacman-2.9.5.orig/scripts/gensync pacman-2.9.5/scripts/gensync
 diff -Naur pacman-2.9.5.orig/scripts/makepkg pacman-2.9.5/scripts/makepkg
 --- pacman-2.9.5.orig/scripts/makepkg	2004-12-19 03:09:59.000000000 +0100
 +++ pacman-2.9.5/scripts/makepkg	2005-05-14 18:31:35.000000000 +0200
+@@ -321,10 +321,10 @@
+ 	exit 1
+ fi
+ 
+-if [ -f $PKGDEST/${pkgname}-${pkgver}-${pkgrel}.fpm -a "$FORCE" = "0" -a "$GENMD5" = "0" ]; then
++if [ -f $PKGDEST/${pkgname}-${pkgver}-${pkgrel}-${CARCH}.fpm -a "$FORCE" = "0" -a "$GENMD5" = "0" ]; then
+ 	if [ "$INSTALL" = "1" ]; then
+ 		warning "a package has already been built, installing existing package."
+-		pacman --upgrade $PKGDEST/${pkgname}-${pkgver}-${pkgrel}.fpm
++		pacman --upgrade $PKGDEST/${pkgname}-${pkgver}-${pkgrel}-${CARCH}.fpm
+ 		exit $?
+ 	else
+ 		error "a package has already been built.  (use -f to overwrite)"
 @@ -670,9 +670,9 @@
  msg "Compressing package..."
  cd $startdir/pkg
@@ -69,6 +82,15 @@ diff -Naur pacman-2.9.5.orig/scripts/makepkg pacman-2.9.5/scripts/makepkg
 +	cmd="tar czvf $PKGDEST/$pkgname-$pkgver-$pkgrel-$CARCH.fpm .PKGINFO .FILELIST *"
  fi
  $cmd | sort >../filelist
+ 
+@@ -691,7 +691,7 @@
+ 
+ if [ "$INSTALL" = "1" -a "`id -u`" = "0" -a "$INFAKEROOT" != "1" ]; then
+ 	msg "Running pacman --upgrade..."
+-	pacman --upgrade $PKGDEST/${pkgname}-${pkgver}-${pkgrel}.fpm
++	pacman --upgrade $PKGDEST/${pkgname}-${pkgver}-${pkgrel}-${CARCH}.fpm
+ 	exit $?
+ fi
  
 diff -Naur pacman-2.9.5.orig/scripts/updatesync pacman-2.9.5/scripts/updatesync
 --- pacman-2.9.5.orig/scripts/updatesync	2004-09-25 19:59:49.000000000 +0200
@@ -82,6 +104,18 @@ diff -Naur pacman-2.9.5.orig/scripts/updatesync pacman-2.9.5/scripts/updatesync
  usage() {
  	echo "updatesync $myver"
  	echo "usage: $0 <action> <destfile> <option> [package_directory]"
+@@ -57,9 +59,9 @@
+ get_md5checksum()
+ {
+ 	if [ "$pkgdir" != "" ]; then
+-		pkgfile="$pkgdir/$pkgname-$pkgver-$pkgrel.fpm"
++		pkgfile="$pkgdir/$pkgname-$pkgver-$pkgrel-$arch.fpm"
+ 	else
+-		pkgfile="$destdir/$pkgname-$pkgver-$pkgrel.fpm"
++		pkgfile="$destdir/$pkgname-$pkgver-$pkgrel-$arch.fpm"
+ 	fi
+ 	if [ -f $pkgfile ]; then
+ 		md5line=`md5sum $pkgfile`
 @@ -88,6 +90,9 @@
  	echo "%DESC%" >>desc
  	echo "$pkgdesc" >>desc
@@ -92,6 +126,18 @@ diff -Naur pacman-2.9.5.orig/scripts/updatesync pacman-2.9.5/scripts/updatesync
  	echo "%CSIZE%" >>desc
  	echo "$csize" >>desc
  	echo "" >>desc
+@@ -206,9 +211,9 @@
+ 
+ 	source $option || die "errors parsing $option"
+ 	if [ "$pkgdir" != "" ]; then
+-		pkgfile="$pkgdir/$pkgname-$pkgver-$pkgrel.fpm"
++		pkgfile="$pkgdir/$pkgname-$pkgver-$pkgrel-$arch.fpm"
+ 	else
+-		pkgfile="$destdir/$pkgname-$pkgver-$pkgrel.fpm"
++		pkgfile="$destdir/$pkgname-$pkgver-$pkgrel-$arch.fpm"
+ 	fi
+ 	[ -f $pkgfile ] || die "missing package file: $pkgfile"
+ 	csize=`du -b $pkgfile | cut -f1`
 diff -Naur pacman-2.9.5.orig/src/pacman.c pacman-2.9.5/src/pacman.c
 --- pacman-2.9.5.orig/src/pacman.c	2005-01-12 00:14:16.000000000 +0100
 +++ pacman-2.9.5/src/pacman.c	2005-05-14 17:32:48.000000000 +0200
