pacman-2.9.6-17-i686 changes in -chroot.diff: chroot_clean() is run before a build(), too copy /etc/makepkg.conf to chroot, too clean diff again, merging krix's ugly hacks (brr)

diff --git a/source/base/pacman/pacman-2.9.6-chroot.diff b/source/base/pacman/pacman-2.9.6-chroot.diff
--- a/source/base/pacman/pacman-2.9.6-chroot.diff
+++ b/source/base/pacman/pacman-2.9.6-chroot.diff
@@ -8,8 +8,8 @@ Description: Adds support for building the package in a chroot.
  scripts/makepkg  |  156 ++++++++++++++++++++++++++++++++++++++++++++++++++++++-
  3 files changed, 215 insertions(+), 1 deletion(-)
 diff -Naur pacman-2.9.6.orig/doc/makepkg.8.in pacman-2.9.6/doc/makepkg.8.in
---- pacman-2.9.6.orig/doc/makepkg.8.in	2005-08-11 23:01:40.000000000 +0200
-+++ pacman-2.9.6/doc/makepkg.8.in	2005-08-11 23:01:53.000000000 +0200
+--- pacman-2.9.6.orig/doc/makepkg.8.in	2005-08-20 00:21:48.000000000 +0200
++++ pacman-2.9.6/doc/makepkg.8.in	2005-08-20 00:20:56.000000000 +0200
 @@ -359,6 +359,58 @@
  to kernel-ide, then subsequent 'pacman -Syu' calls will not pick up the upgrade, due
  to the differing package names.  \fIreplaces\fP handles this.
@@ -80,8 +80,8 @@ diff -Naur pacman-2.9.6.orig/doc/makepkg.8.in pacman-2.9.6/doc/makepkg.8.in
  Install missing dependencies using pacman.  When makepkg finds missing build-time
  or run-time dependencies, it will run pacman to try and resolve them.  If successful,
 diff -Naur pacman-2.9.6.orig/etc/makepkg.conf pacman-2.9.6/etc/makepkg.conf
---- pacman-2.9.6.orig/etc/makepkg.conf	2005-08-11 23:01:40.000000000 +0200
-+++ pacman-2.9.6/etc/makepkg.conf	2005-08-11 23:01:53.000000000 +0200
+--- pacman-2.9.6.orig/etc/makepkg.conf	2005-08-20 00:21:48.000000000 +0200
++++ pacman-2.9.6/etc/makepkg.conf	2005-08-20 00:20:56.000000000 +0200
 @@ -28,6 +28,11 @@
  # Enable fakeroot for building packages as a non-root user
  export USE_FAKEROOT="y"
@@ -95,8 +95,8 @@ diff -Naur pacman-2.9.6.orig/etc/makepkg.conf pacman-2.9.6/etc/makepkg.conf
  export USE_COLOR="y"
  
 diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
---- pacman-2.9.6.orig/scripts/makepkg	2005-08-11 23:01:40.000000000 +0200
-+++ pacman-2.9.6/scripts/makepkg	2005-08-11 23:02:51.000000000 +0200
+--- pacman-2.9.6.orig/scripts/makepkg	2005-08-20 00:21:48.000000000 +0200
++++ pacman-2.9.6/scripts/makepkg	2005-08-20 00:32:40.000000000 +0200
 @@ -40,6 +40,12 @@
  	shift
  fi
@@ -118,7 +118,7 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
  	echo "  -s, --syncdeps   Install missing dependencies with pacman"
  	echo "  -S, --sudosync   Install missing dependencies with pacman and sudo"
  	echo "  -u, --noup2date  Do not check for newer version"
-@@ -226,6 +233,34 @@
+@@ -226,6 +233,58 @@
  	echo
  }
  
@@ -150,10 +150,34 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
 +    fi
 +    msg "Successfully mounted chroot directories."
 +}
++
++chroot_clean()
++{
++	if [ "$CHROOT" = "1" ]; then
++		msg "Cleaning chroot."
++		rm -rf $CHROOTDIR/var/tmp/fst/*
++		msg "Removing unnecessary packages."
++		for i in "$COREPKGS"
++		do
++			corelist="$corelist `pacman -r $CHROOTDIR -Sg $i|grep -v '^\w'`"
++		done
++		for i in `pacman -r $CHROOTDIR -Q|sed 's/\([^ ]*\) .*/\1/'`
++		do
++			if ! echo $corelist |grep -q $i; then
++				removelist="$removelist $i"
++			fi
++		done
++		pacman -r $CHROOTDIR -Rc $removelist --noconfirm
++		if [ "$?" != "0" ]; then
++			error "Failed to remove packages."
++			exit 1
++		fi
++	fi
++}
  
  # Options
  CLEANUP=0
-@@ -245,6 +280,7 @@
+@@ -245,6 +304,7 @@
  NOSTRIP=0
  NOBUILD=0
  RMDEPS=0
@@ -161,7 +185,7 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
  LOGGING=0
  NOUP2DATE=0
  BUILDSCRIPT="./FrugalBuild"
-@@ -271,6 +307,7 @@
+@@ -271,6 +331,7 @@
  		--gensha1)    GENSHA1=1 ;;
  		--genmd5)     GENMD5=1 ;;
  		--rmdeps)     RMDEPS=1 ;;
@@ -169,7 +193,7 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
  		--noup2date)     NOUP2DATE=1 ;;
  		--logging)    LOGGING=1 ;;
  		--help)
-@@ -282,7 +319,7 @@
+@@ -282,7 +343,7 @@
  			exit 1
  			;;
  		-*)
@@ -178,7 +202,7 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
  				case $opt in
  					a) SEARCHDEPS=1 ;;
  					c) CLEANUP=1 ;;
-@@ -308,6 +345,7 @@
+@@ -308,6 +369,7 @@
  					o) NOBUILD=1 ;;
  					p) BUILDSCRIPT=$OPTARG ;;
  					r) RMDEPS=1 ;;
@@ -186,34 +210,15 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
  					s) DEP_BIN=1 ;;
  					S) DEP_SUDO=1 ;;
  					u) NOUP2DATE=1 ;;
-@@ -343,6 +381,26 @@
+@@ -343,6 +405,7 @@
  	if [ "`id -u`" = "0" -a "$INFAKEROOT" != "1" ]; then
  		msg "Cleaning up source files from the cache."
  		rm -rf /var/cache/pacman/src/*
-+		if [ "$CHROOT" = "1" ]; then
-+			msg "Cleaning chroot."
-+			rm -rf $CHROOTDIR/var/tmp/fst/*
-+			msg "Removing unnecessary packages."
-+			for i in "$COREPKGS"
-+			do
-+				corelist="$corelist `pacman -r $CHROOTDIR -Sg $i|grep -v '^\w'`"
-+			done
-+			for i in `pacman -r $CHROOTDIR -Q|sed 's/\([^ ]*\) .*/\1/'`
-+			do
-+				if ! echo $corelist |grep -q $i; then
-+					removelist="$removelist $i"
-+				fi
-+			done
-+			pacman -r $CHROOTDIR -Rc $removelist --noconfirm
-+			if [ "$?" != "0" ]; then
-+				error "Failed to remove packages."
-+				exit 1
-+			fi
-+		fi
++		chroot_clean
  		exit 0
  	else
  		error "You must be root to clean the cache."
-@@ -436,6 +494,93 @@
+@@ -436,6 +499,100 @@
  	fi
  fi
  
@@ -242,6 +247,7 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
 +	install -d -m 2775 {,$CHROOTDIR}/var/cache/ccache/$pkgname
 +
 +	chroot_mount
++	chroot_clean
 +
 +	if [ ! -d "$CHROOTDIR/usr" ]; then
 +		msg "Building chroot environment"
@@ -249,6 +255,8 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
 +		if [ "$?" != "0" ]; then
 +			error "Failed to build chroot environment."
 +			chroot_umount
++			msg "Removing lock file..."
++			rm -f $CHROOTDIR/var/tmp/fst/lock
 +			exit 1
 +		fi
 +	else
@@ -259,11 +267,14 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
 +		if [ "$?" != "0" ]; then
 +			error "Failed to update chroot environment."
 +			chroot_umount
++			msg "Removing lock file..."
++			rm -f $CHROOTDIR/var/tmp/fst/lock
 +			exit 1
 +		fi
 +	fi
 +	
 +	msg "Copying config files to chroot"
++	cp -pf /etc/makepkg.conf $CHROOTDIR/etc >/dev/null &
 +	cp -pf /etc/resolv.conf $CHROOTDIR/etc >/dev/null &
 +	cp -pf /etc/passwd $CHROOTDIR/etc >/dev/null &
 +	cp -pf /etc/shadow $CHROOTDIR/etc >/dev/null &
@@ -301,13 +312,14 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
 +	fi
 +
 +	chroot_umount
++	rm -f $CHROOTDIR/var/tmp/fst/lock
 +	exit 0
 +fi
 +
  # Enter the fakeroot environment if necessary.  This will call the makepkg script again
  # as the fake root user.  We detect this by passing a sentinel option (-F) to makepkg
  if [ "`id -u`" != "0" ]; then
-@@ -758,6 +903,10 @@
+@@ -758,6 +915,10 @@
  # use ccache if it's available
  if [ "$NOCCACHE" = "0" ]; then
  	[ -d /usr/lib/ccache/bin ] && export PATH=/usr/lib/ccache/bin:$PATH
@@ -318,7 +330,7 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
  fi
  
  # build
-@@ -940,8 +1089,13 @@
+@@ -940,8 +1101,13 @@
  if [ -f $startdir/pkg/.CHANGELOG ]; then
  	extra="$extra .CHANGELOG"
  fi
@@ -332,32 +344,3 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
  
  cd $startdir
  if [ "$SEARCHDEPS" == "1" ]; then
-diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
---- pacman-2.9.6.orig/scripts/makepkg	2005-08-12 18:27:21.000000000 +0200
-+++ pacman-2.9.6/scripts/makepkg	2005-08-12 18:29:41.000000000 +0200
-@@ -526,6 +526,8 @@
- 		if [ "$?" != "0" ]; then
- 			error "Failed to build chroot environment."
- 			chroot_umount
-+			msg "Removing lock file..."
-+			rm -f $CHROOTDIR/var/tmp/fst/lock
- 			exit 1
- 		fi
- 	else
-@@ -536,6 +538,8 @@
- 		if [ "$?" != "0" ]; then
- 			error "Failed to update chroot environment."
- 			chroot_umount
-+			msg "Removing lock file..."
-+			rm -f $CHROOTDIR/var/tmp/fst/lock
- 			exit 1
- 		fi
- 	fi
-@@ -578,6 +582,7 @@
- 	fi
- 
- 	chroot_umount
-+	rm -f $CHROOTDIR/var/tmp/fst/lock
- 	exit 0
- fi
- 
