pacman-2.9.6-15-x86_64   * Fix locking problems (same problem was the mount)

diff --git a/source/base/pacman/pacman-2.9.6-chroot.diff b/source/base/pacman/pacman-2.9.6-chroot.diff
--- a/source/base/pacman/pacman-2.9.6-chroot.diff
+++ b/source/base/pacman/pacman-2.9.6-chroot.diff
@@ -332,3 +332,32 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
  
  cd $startdir
  if [ "$SEARCHDEPS" == "1" ]; then
+diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
+--- pacman-2.9.6.orig/scripts/makepkg	2005-08-12 18:27:21.000000000 +0200
++++ pacman-2.9.6/scripts/makepkg	2005-08-12 18:29:41.000000000 +0200
+@@ -526,6 +526,8 @@
+ 		if [ "$?" != "0" ]; then
+ 			error "Failed to build chroot environment."
+ 			chroot_umount
++			msg "Removing lock file..."
++			rm -f $CHROOTDIR/var/tmp/fst/lock
+ 			exit 1
+ 		fi
+ 	else
+@@ -536,6 +538,8 @@
+ 		if [ "$?" != "0" ]; then
+ 			error "Failed to update chroot environment."
+ 			chroot_umount
++			msg "Removing lock file..."
++			rm -f $CHROOTDIR/var/tmp/fst/lock
+ 			exit 1
+ 		fi
+ 	fi
+@@ -578,6 +582,7 @@
+ 	fi
+ 
+ 	chroot_umount
++	rm -f $CHROOTDIR/var/tmp/fst/lock
+ 	exit 0
+ fi
+ 
