pacman-2.9.5-12-i686 the install directive is no longer needed if the scripts's name is $pkgname.install removed hack for gensync - no longer needed, all pkgs use the new -up2date.diff added support for using != i686-optimized pkgs from any mirror some fixes in connection with the nobuild directive

diff --git a/source/base/pacman/pacman-2.9.5-nobuild.diff b/source/base/pacman/pacman-2.9.5-nobuild.diff
--- a/source/base/pacman/pacman-2.9.5-nobuild.diff
+++ b/source/base/pacman/pacman-2.9.5-nobuild.diff
@@ -1,25 +1,3 @@
-diff -Naur pacman-2.9.5.orig/scripts/gensync pacman-2.9.5/scripts/gensync
---- pacman-2.9.5.orig/scripts/gensync	2005-05-20 21:16:19.000000000 +0200
-+++ pacman-2.9.5/scripts/gensync	2005-05-20 21:18:03.000000000 +0200
-@@ -75,6 +75,7 @@
- 	cat $1 |grep -v "up2date=\`" >/tmp/.FrugalBuild
- 	source /tmp/.FrugalBuild || return 1
- 	rm /tmp/.FrugalBuild
-+	[ "$nobuild" ] && return 0
- 	cd $gstmpdir
- 	mkdir $pkgname-$pkgver-$pkgrel || return 1
- 	cd $pkgname-$pkgver-$pkgrel
-diff -Naur pacman-2.9.5.orig/scripts/updatesync pacman-2.9.5/scripts/updatesync
---- pacman-2.9.5.orig/scripts/updatesync	2005-05-20 22:09:44.000000000 +0200
-+++ pacman-2.9.5/scripts/updatesync	2005-05-20 22:10:36.000000000 +0200
-@@ -74,6 +74,7 @@
- 	unset pkgname pkgver pkgrel pkgdesc force
- 	unset groups replaces provides depends conflicts
- 	source $1 || return 1
-+	[ "$nobuild" ] && return 0
- 	cd $ustmpdir
- 	mkdir $pkgname-$pkgver-$pkgrel || return 1
- 	cd $pkgname-$pkgver-$pkgrel
 diff -Naur pacman-2.9.5.orig/doc/makepkg.8.in pacman-2.9.5/doc/makepkg.8.in
 --- pacman-2.9.5.orig/doc/makepkg.8.in	2004-08-04 07:57:17.000000000 +0200
 +++ pacman-2.9.5/doc/makepkg.8.in	2005-05-20 21:28:51.000000000 +0200
@@ -36,3 +14,35 @@ diff -Naur pacman-2.9.5.orig/doc/makepkg.8.in pacman-2.9.5/doc/makepkg.8.in
  .B url
  This field contains an optional URL that is associated with the piece of software
  being packaged.  This is typically the project's website.
+diff -Naur pacman-2.9.5.orig/scripts/gensync pacman-2.9.5/scripts/gensync
+--- pacman-2.9.5.orig/scripts/gensync	2004-10-23 19:27:07.000000000 +0200
++++ pacman-2.9.5/scripts/gensync	2005-05-23 14:03:25.000000000 +0200
+@@ -163,7 +163,9 @@
+ echo "gensync: building database entries, generating md5sums..." >&2
+ cd `dirname $2`
+ for file in `find $rootdir/* -name FrugalBuild`; do
++	unset nobuild
+ 	source $file || die "errors parsing $file"
++	[ "$nobuild" ] && continue
+ 	if [ "$pkgdir" != "" ]; then
+ 		pkgfile="$pkgdir/$pkgname-$pkgver-$pkgrel.pkg.tar.gz"
+ 	else
+diff -Naur pacman-2.9.5.orig/scripts/updatesync pacman-2.9.5/scripts/updatesync
+--- pacman-2.9.5.orig/scripts/updatesync	2004-09-25 19:59:49.000000000 +0200
++++ pacman-2.9.5/scripts/updatesync	2005-05-23 14:04:32.000000000 +0200
+@@ -205,6 +205,7 @@
+ 	delete_entry $option
+ 
+ 	source $option || die "errors parsing $option"
++	if [ ! "$nobuild" ]; then
+ 	if [ "$pkgdir" != "" ]; then
+ 		pkgfile="$pkgdir/$pkgname-$pkgver-$pkgrel.pkg.tar.gz"
+ 	else
+@@ -216,6 +217,7 @@
+ 	[ -z $pkgmd5sum ] && die "error generating checksum for $pkgfile"
+ 	echo "updatesync: creating entry for $option" >&2
+ 	db_write_entry $option || die "error writing entry for $option"
++	fi
+ else
+ 	# DELETE
+ 	delete_entry $option
