pacman-2.9.7-1-i686 as planned, merged -optcorrect.diff to -chroot.diff

diff --git a/source/base/pacman/pacman-2.9.7-chroot.diff b/source/base/pacman/pacman-2.9.7-chroot.diff
--- a/source/base/pacman/pacman-2.9.7-chroot.diff
+++ b/source/base/pacman/pacman-2.9.7-chroot.diff
@@ -132,7 +132,7 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
  	echo "  -s, --syncdeps   Install missing dependencies with pacman"
  	echo "  -S, --sudosync   Install missing dependencies with pacman and sudo"
  	echo "  -u, --noup2date  Do not check for newer version"
-@@ -226,6 +240,58 @@
+@@ -226,6 +240,60 @@
  	echo
  }
  
@@ -181,10 +181,12 @@ diff -Naur pacman-2.9.6.orig/scripts/makepkg pacman-2.9.6/scripts/makepkg
 +				removelist="$removelist $i"
 +			fi
 +		done
-+		pacman -r $CHROOTDIR -Rc $removelist --noconfirm
-+		if [ "$?" != "0" ]; then
-+			error "Failed to remove packages."
-+			exit 1
++		if [ ! -z "$removelist" ]; then
++			pacman -r $CHROOTDIR -Rc $removelist --noconfirm
++			if [ "$?" != "0" ]; then
++				error "Failed to remove packages."
++				exit 1
++			fi
 +		fi
 +	fi
 +}
