plasma-workspace-5.8.1-4-x86_64 * patch out yet another variant of libexec -> CMAKE_INSTALL_FULL_LIBEXECDIR_KF5

diff --git a/source/plasma/plasma-workspace/startkde.patch b/source/plasma/plasma-workspace/startkde.patch
--- a/source/plasma/plasma-workspace/startkde.patch
+++ b/source/plasma/plasma-workspace/startkde.patch
@@ -1,6 +1,6 @@
 diff -Naur plasma-workspace-5.8.1/startkde/startkde.cmake plasma-workspace-5.8.1-p/startkde/startkde.cmake
 --- plasma-workspace-5.8.1/startkde/startkde.cmake	2016-10-11 14:46:00.000000000 +0200
-+++ plasma-workspace-5.8.1-p/startkde/startkde.cmake	2016-10-12 15:39:02.918845003 +0200
++++ plasma-workspace-5.8.1-p/startkde/startkde.cmake	2016-10-14 19:03:03.899587814 +0200
 @@ -3,13 +3,6 @@
  #  DEFAULT KDE STARTUP SCRIPT ( @PROJECT_VERSION@ )
  #
@@ -91,6 +91,15 @@ diff -Naur plasma-workspace-5.8.1/startkde/startkde.cmake plasma-workspace-5.8.1
  
  # Mark that full KDE session is running (e.g. Konqueror preloading works only
  # with full KDE running). The KDE_FULL_SESSION property can be detected by
+@@ -350,7 +297,7 @@
+ 
+ # We set LD_BIND_NOW to increase the efficiency of kdeinit.
+ # kdeinit unsets this variable before loading applications.
+-LD_BIND_NOW=true @CMAKE_INSTALL_FULL_LIBEXECDIR_KF5@/start_kdeinit_wrapper --kded +kcminit_startup
++LD_BIND_NOW=true @CMAKE_INSTALL_FULL_LIBEXECDIR@/start_kdeinit_wrapper --kded +kcminit_startup
+ if test $? -ne 0; then
+   # Startup error
+   echo 'startkde: Could not start kdeinit5. Check your installation.'  1>&2
 @@ -359,7 +306,7 @@
    exit 1
  fi
@@ -122,7 +131,7 @@ diff -Naur plasma-workspace-5.8.1/startkde/startkde.cmake plasma-workspace-5.8.1
          fi
 diff -Naur plasma-workspace-5.8.1/startkde/startplasma.cmake plasma-workspace-5.8.1-p/startkde/startplasma.cmake
 --- plasma-workspace-5.8.1/startkde/startplasma.cmake	2016-10-11 14:46:00.000000000 +0200
-+++ plasma-workspace-5.8.1-p/startkde/startplasma.cmake	2016-10-12 15:41:07.290846846 +0200
++++ plasma-workspace-5.8.1-p/startkde/startplasma.cmake	2016-10-14 19:03:03.900587814 +0200
 @@ -49,18 +49,6 @@
    esac
  fi
@@ -142,6 +151,15 @@ diff -Naur plasma-workspace-5.8.1/startkde/startplasma.cmake plasma-workspace-5.
  
  # Activate the kde font directories.
  #
+@@ -131,7 +119,7 @@
+ 
+ # We set LD_BIND_NOW to increase the efficiency of kdeinit.
+ # kdeinit unsets this variable before loading applications.
+-LD_BIND_NOW=true @CMAKE_INSTALL_FULL_LIBEXECDIR_KF5@/start_kdeinit_wrapper --kded +kcminit_startup
++LD_BIND_NOW=true @CMAKE_INSTALL_FULL_LIBEXECDIR@/start_kdeinit_wrapper --kded +kcminit_startup
+ if test $? -ne 0; then
+   # Startup error
+   echo 'startplasma: Could not start kdeinit5. Check your installation.'  1>&2
 @@ -140,7 +128,7 @@
    exit 1
  fi
@@ -173,7 +191,7 @@ diff -Naur plasma-workspace-5.8.1/startkde/startplasma.cmake plasma-workspace-5.
          fi
 diff -Naur plasma-workspace-5.8.1/startkde/startplasmacompositor.cmake plasma-workspace-5.8.1-p/startkde/startplasmacompositor.cmake
 --- plasma-workspace-5.8.1/startkde/startplasmacompositor.cmake	2016-10-11 14:46:00.000000000 +0200
-+++ plasma-workspace-5.8.1-p/startkde/startplasmacompositor.cmake	2016-10-12 15:43:50.158849260 +0200
++++ plasma-workspace-5.8.1-p/startkde/startplasmacompositor.cmake	2016-10-14 19:03:03.901587814 +0200
 @@ -3,18 +3,6 @@
  #  DEFAULT KDE STARTUP SCRIPT ( @PROJECT_VERSION@ )
  #
