e2fsprogs-1.41.10-1-i686
- version bump

diff --git a/source/base/e2fsprogs/FrugalBuild b/source/base/e2fsprogs/FrugalBuild
--- a/source/base/e2fsprogs/FrugalBuild
+++ b/source/base/e2fsprogs/FrugalBuild
@@ -2,7 +2,7 @@
 # Maintainer: Miklos Vajna <vmiklos@frugalware.org>
 
 pkgname=e2fsprogs
-pkgver=1.41.9
+pkgver=1.41.10
 pkgrel=1
 pkgdesc="Utilities needed to create and maintain ext2 and ext3 filesystems"
 depends=('glibc>=2.8-3' 'util-linux-ng>=2.16')
@@ -13,15 +13,19 @@ _F_sourceforge_prefix="libs-"
 Finclude sourceforge
 url="http://e2fsprogs.sourceforge.net/"
 source=($source rc.fsck rc.random)
-sha1sums=('e30d6bc67ac7b14cd817986c9bff13fb695d7a35' \
+sha1sums=('18fa09e34009c5fcbce40461ac435ddcce0fee39' \
           'a30724dc241e53dbf0c90d2256989e4f87bdb6e4' \
           '7d5e3eecbea952aa1f72808fb810892d82a35461')
 
 build()
 {
-	Fmake --with-ccopts="$CFLAGS" --enable-elf-shlibs --enable-dynamic-e2fsck \
+	Fmake --enable-elf-shlibs --enable-dynamic-e2fsck \
 		--with-root-prefix="" --disable-libblkid \
 		--disable-libuuid --disable-libuuidd
+	# it seems building the test binaries fails
+	if [ "$CARCH" != "ppc" ]; then
+		make check || return 1
+	fi
 	make DESTDIR=$Fdestdir install install-libs
 	Frcd fsck
 	Frcd random
