kblogger-0.6.5-1-i686   version bump   reworked patch

diff --git a/source/kde-extra/kblogger/admin.patch b/source/kde-extra/kblogger/admin.patch
--- a/source/kde-extra/kblogger/admin.patch
+++ b/source/kde-extra/kblogger/admin.patch
@@ -1,6 +1,6 @@
-diff -Naurp kblogger-0.6.2/admin/cvs.sh kblogger-0.6.2-p/admin/cvs.sh
---- kblogger-0.6.2/admin/cvs.sh	2005-09-24 22:49:40.000000000 +0200
-+++ kblogger-0.6.2-p/admin/cvs.sh	2006-11-01 01:19:20.000000000 +0100
+diff -Naurp kblogger-0.6.5/admin/cvs.sh kblogger-0.6.5-p/admin/cvs.sh
+--- kblogger-0.6.5/admin/cvs.sh	2005-09-24 22:49:40.000000000 +0200
++++ kblogger-0.6.5-p/admin/cvs.sh	2007-03-24 21:56:31.000000000 +0100
 @@ -32,7 +32,7 @@ check_autotool_versions()
  required_autoconf_version="2.53 or newer"
  AUTOCONF_VERSION=`$AUTOCONF --version | head -n 1`
@@ -19,3 +19,12 @@ diff -Naurp kblogger-0.6.2/admin/cvs.sh kblogger-0.6.2-p/admin/cvs.sh
    "" )
      echo "*** AUTOHEADER NOT FOUND!."
      echo "*** KDE requires autoheader $required_autoconf_version"
+@@ -68,7 +68,7 @@ case $AUTOMAKE_STRING in
+     echo "*** KDE requires automake $required_automake_version"
+     exit 1
+     ;;
+-  automake*1.6.* | automake*1.7* | automake*1.8* | automake*1.9*)
++  automake*1.6.* | automake*1.7* | automake*1.8* | automake*1.9* | automake*1.1* )
+     echo "*** $AUTOMAKE_STRING found."
+     UNSERMAKE=no
+     ;;
