pygobject-2.18.0-2-i686
- update detect_libffi.patch from bouleetbil :)

diff --git a/source/lib/pygobject/detect_libffi.patch b/source/lib/pygobject/detect_libffi.patch
--- a/source/lib/pygobject/detect_libffi.patch
+++ b/source/lib/pygobject/detect_libffi.patch
@@ -1,6 +1,6 @@
---- pygobject-2.16.0/configure	2009-01-04 21:34:55.000000000 +0100
-+++ pygobject-2.16.0/configure	2009-01-11 14:02:41.000000000 +0100
-@@ -12491,6 +12491,176 @@
+--- pygobject-2.18.0old/configure	2009-05-24 22:37:48.000000000 +0200
++++ pygobject-2.18.0/configure	2009-05-27 20:26:38.000000000 +0200
+@@ -12888,6 +12888,176 @@
  fi
  
  
@@ -169,11 +169,125 @@
 +if test "$pygobject_ffi_h" = "yes"; then
 +  HAVE_LIBFFI_TRUE=
 +  HAVE_LIBFFI_FALSE='#'
-+  have_libffi=true
++  have_libffi=True
 +else
 +  HAVE_LIBFFI_TRUE='#'
 +  HAVE_LIBFFI_FALSE=
 +fi
  
  
+ 
+@@ -13927,115 +14097,6 @@
+   exec_prefix=$exec_prefix_save
+ 
+ 
+-{ $as_echo "$as_me:$LINENO: checking for ffi" >&5
+-$as_echo_n "checking for ffi... " >&6; }
+-
+-# Check whether --with-ffi was given.
+-if test "${with_ffi+set}" = set; then
+-  withval=$with_ffi; with_libffi=$withval
+-else
+-  with_libffi=auto
+-fi
+-
+-if test x"$with_libffi" = xno ; then
+-  have_libffi=false
+-else
+-
+-pkg_failed=no
+-{ $as_echo "$as_me:$LINENO: checking for FFI" >&5
+-$as_echo_n "checking for FFI... " >&6; }
+-
+-if test -n "$PKG_CONFIG"; then
+-    if test -n "$FFI_CFLAGS"; then
+-        pkg_cv_FFI_CFLAGS="$FFI_CFLAGS"
+-    else
+-        if test -n "$PKG_CONFIG" && \
+-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libffi >= 3.0\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "libffi >= 3.0") 2>&5
+-  ac_status=$?
+-  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); }; then
+-  pkg_cv_FFI_CFLAGS=`$PKG_CONFIG --cflags "libffi >= 3.0" 2>/dev/null`
+-else
+-  pkg_failed=yes
+-fi
+-    fi
+-else
+-	pkg_failed=untried
+-fi
+-if test -n "$PKG_CONFIG"; then
+-    if test -n "$FFI_LIBS"; then
+-        pkg_cv_FFI_LIBS="$FFI_LIBS"
+-    else
+-        if test -n "$PKG_CONFIG" && \
+-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libffi >= 3.0\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "libffi >= 3.0") 2>&5
+-  ac_status=$?
+-  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); }; then
+-  pkg_cv_FFI_LIBS=`$PKG_CONFIG --libs "libffi >= 3.0" 2>/dev/null`
+-else
+-  pkg_failed=yes
+-fi
+-    fi
+-else
+-	pkg_failed=untried
+-fi
+-
+-
+-
+-if test $pkg_failed = yes; then
+-
+-if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+-        _pkg_short_errors_supported=yes
+-else
+-        _pkg_short_errors_supported=no
+-fi
+-        if test $_pkg_short_errors_supported = yes; then
+-	        FFI_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libffi >= 3.0"`
+-        else
+-	        FFI_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libffi >= 3.0"`
+-        fi
+-	# Put the nasty error message in config.log where it belongs
+-	echo "$FFI_PKG_ERRORS" >&5
+-
+-	{ $as_echo "$as_me:$LINENO: result: no" >&5
+-$as_echo "no" >&6; }
+-                have_libffi=no
+-elif test $pkg_failed = untried; then
+-	have_libffi=no
+-else
+-	FFI_CFLAGS=$pkg_cv_FFI_CFLAGS
+-	FFI_LIBS=$pkg_cv_FFI_LIBS
+-        { $as_echo "$as_me:$LINENO: result: yes" >&5
+-$as_echo "yes" >&6; }
+-	have_libffi=yes
+-fi
+-fi
+-if test x"$with_libffi" = xyes && test x"$have_libffi" = xno ; then
+-  { { $as_echo "$as_me:$LINENO: error: ffi requested, but not found" >&5
+-$as_echo "$as_me: error: ffi requested, but not found" >&2;}
+-   { (exit 1); exit 1; }; }
+-fi
+-if test x"$have_libffi" = xyes; then
+-
+-cat >>confdefs.h <<\_ACEOF
+-#define HAVE_FFI_H 1
+-_ACEOF
+-
+-  LIBFFI_PC=libffi
+-fi
+-{ $as_echo "$as_me:$LINENO: result: $have_libffi" >&5
+-$as_echo "$have_libffi" >&6; }
+- if test "$have_libffi" = "yes"; then
+-  HAVE_LIBFFI_TRUE=
+-  HAVE_LIBFFI_FALSE='#'
+-else
+-  HAVE_LIBFFI_TRUE='#'
+-  HAVE_LIBFFI_FALSE=
+-fi
+-
+-
  
