sim-0.9.4.2-1-i686 * Version bump * reworked the patch and renamed to frugalware.patch

diff --git a/source/kde-extra/sim/frugalware.patch b/source/kde-extra/sim/frugalware.patch
--- a/source/kde-extra/sim/frugalware.patch
+++ b/source/kde-extra/sim/frugalware.patch
@@ -1,7 +1,19 @@
-diff -Nurp sim-0.9.4.1/plugins/remote/Makefile.am sim-0.9.4.1-p/plugins/remote/Makefile.am
---- sim-0.9.4.1/plugins/remote/Makefile.am	2006-02-03 10:54:16.000000000 +0100
-+++ sim-0.9.4.1-p/plugins/remote/Makefile.am	2006-10-24 19:31:17.000000000 +0200
-@@ -11,7 +11,7 @@ simctrl_SOURCES = \
+diff -Naur sim-0.9.4.2/admin/cvs.sh sim-0.9.4.2-p/admin/cvs.sh
+--- sim-0.9.4.2/admin/cvs.sh	2006-07-09 12:39:25.000000000 +0200
++++ sim-0.9.4.2-p/admin/cvs.sh	2007-01-20 03:45:34.000000000 +0100
+@@ -66,7 +66,7 @@
+     echo "*** SIM requires automake $required_automake_version"
+     exit 1
+     ;;
+-  automake*1.6.* | automake*1.7* | automake*1.8* | automake*1.9*) : ;;
++  automake*1.6.* | automake*1.7* | automake*1.8* | automake*1.9* | automake*1.10* ) : ;;
+   "" )
+     echo "*** AUTOMAKE NOT FOUND!."
+     echo "*** SIM requires automake $required_automake_version"
+diff -Naur sim-0.9.4.2/plugins/remote/Makefile.am sim-0.9.4.2-p/plugins/remote/Makefile.am
+--- sim-0.9.4.2/plugins/remote/Makefile.am	2006-02-03 10:54:16.000000000 +0100
++++ sim-0.9.4.2-p/plugins/remote/Makefile.am	2007-01-20 03:44:57.000000000 +0100
+@@ -11,7 +11,7 @@
  
  INCLUDES=-I../../sim -I../_core $(all_includes)
  
@@ -10,31 +22,10 @@ diff -Nurp sim-0.9.4.1/plugins/remote/Makefile.am sim-0.9.4.1-p/plugins/remote/M
  mimedir = $(kde_mimedir)/application
  service_DATA = simctrl.desktop
  servicedir = $(kde_servicesdir)
-diff -Nurp sim-0.9.4.1/plugins/remote/Makefile.in sim-0.9.4.1-p/plugins/remote/Makefile.in
---- sim-0.9.4.1/plugins/remote/Makefile.in	2006-10-21 19:10:31.000000000 +0200
-+++ sim-0.9.4.1-p/plugins/remote/Makefile.in	2006-10-24 19:30:13.000000000 +0200
-@@ -381,7 +381,7 @@ simctrl_SOURCES = \
-  simctrl.cpp
- 
- INCLUDES = -I../../sim -I../_core $(all_includes)
--mime_DATA = x-icq.desktop
-+mime_DATA = x-sim-icq.desktop
- mimedir = $(kde_mimedir)/application
- service_DATA = simctrl.desktop
- servicedir = $(kde_servicesdir)
-@@ -791,7 +791,7 @@ clean-metasources:
- 	-rm -f  remotecfg.moc remote.moc
- 
- #>+ 2
--KDE_DIST=simremote.vcproj remote.h remotecfg.h simext.def simremote.rc simipc.vcproj simipc.cpp SimControl.cpp simext.vcproj simctrl.vcproj SimControl.rgs simext.cpp Makefile.in sim_remote.cpp SIM_ext.h IContextMenuImpl.h simctrl.dsp x-icq.desktop SIM_ext.rgs SimControl.h simext.idl simext.dsp SIM_ext.cpp IShellExtInitImpl.h remote.rc simremote.idl simext.rc remotecfgbase.ui remote.vcproj configure.in.in simctrl.desktop simremote.def simremote.dsp Makefile.am remote.dsp simipc.dsp 
-+KDE_DIST=simremote.vcproj remote.h remotecfg.h simext.def simremote.rc simipc.vcproj simipc.cpp SimControl.cpp simext.vcproj simctrl.vcproj SimControl.rgs simext.cpp Makefile.in sim_remote.cpp SIM_ext.h IContextMenuImpl.h simctrl.dsp x-sim-icq.desktop SIM_ext.rgs SimControl.h simext.idl simext.dsp SIM_ext.cpp IShellExtInitImpl.h remote.rc simremote.idl simext.rc remotecfgbase.ui remote.vcproj configure.in.in simctrl.desktop simremote.def simremote.dsp Makefile.am remote.dsp simipc.dsp 
- 
- #>+ 4
- clean-ui:
-diff -Nurp sim-0.9.4.1/plugins/remote/simctrl.desktop sim-0.9.4.1-p/plugins/remote/simctrl.desktop
---- sim-0.9.4.1/plugins/remote/simctrl.desktop	2006-01-15 13:53:27.000000000 +0100
-+++ sim-0.9.4.1-p/plugins/remote/simctrl.desktop	2006-10-24 19:31:57.000000000 +0200
-@@ -3,7 +3,7 @@ Encoding=UTF-8
+diff -Naur sim-0.9.4.2/plugins/remote/simctrl.desktop sim-0.9.4.2-p/plugins/remote/simctrl.desktop
+--- sim-0.9.4.2/plugins/remote/simctrl.desktop	2006-01-15 13:53:27.000000000 +0100
++++ sim-0.9.4.2-p/plugins/remote/simctrl.desktop	2007-01-20 03:44:57.000000000 +0100
+@@ -3,7 +3,7 @@
  Name=simctrl
  Icon=licq
  Type=Service
@@ -43,9 +34,9 @@ diff -Nurp sim-0.9.4.1/plugins/remote/simctrl.desktop sim-0.9.4.1-p/plugins/remo
  GenericName=SIM remote control
  Terminal=false
  Exec=simctrl
-diff -Nurp sim-0.9.4.1/plugins/remote/x-icq.desktop sim-0.9.4.1-p/plugins/remote/x-icq.desktop
---- sim-0.9.4.1/plugins/remote/x-icq.desktop	2006-01-15 13:53:27.000000000 +0100
-+++ sim-0.9.4.1-p/plugins/remote/x-icq.desktop	1970-01-01 01:00:00.000000000 +0100
+diff -Naur sim-0.9.4.2/plugins/remote/x-icq.desktop sim-0.9.4.2-p/plugins/remote/x-icq.desktop
+--- sim-0.9.4.2/plugins/remote/x-icq.desktop	2006-01-15 13:53:27.000000000 +0100
++++ sim-0.9.4.2-p/plugins/remote/x-icq.desktop	1970-01-01 01:00:00.000000000 +0100
 @@ -1,51 +0,0 @@
 -[Desktop Entry]
 -Encoding=UTF-8
@@ -98,9 +89,9 @@ diff -Nurp sim-0.9.4.1/plugins/remote/x-icq.desktop sim-0.9.4.1-p/plugins/remote
 -MimeType=application/x-icq
 -Patterns=*.uin;*.icq
 -Icon=licq
-diff -Nurp sim-0.9.4.1/plugins/remote/x-sim-icq.desktop sim-0.9.4.1-p/plugins/remote/x-sim-icq.desktop
---- sim-0.9.4.1/plugins/remote/x-sim-icq.desktop	1970-01-01 01:00:00.000000000 +0100
-+++ sim-0.9.4.1-p/plugins/remote/x-sim-icq.desktop	2006-10-24 19:32:48.000000000 +0200
+diff -Naur sim-0.9.4.2/plugins/remote/x-sim-icq.desktop sim-0.9.4.2-p/plugins/remote/x-sim-icq.desktop
+--- sim-0.9.4.2/plugins/remote/x-sim-icq.desktop	1970-01-01 01:00:00.000000000 +0100
++++ sim-0.9.4.2-p/plugins/remote/x-sim-icq.desktop	2007-01-20 03:44:57.000000000 +0100
 @@ -0,0 +1,51 @@
 +[Desktop Entry]
 +Encoding=UTF-8
