superkaramba-0.39-3-i686 * Updated the patch to work with new automake

diff --git a/source/kde-extra/superkaramba/py25_and_admin.patch b/source/kde-extra/superkaramba/py25_and_admin.patch
--- a/source/kde-extra/superkaramba/py25_and_admin.patch
+++ b/source/kde-extra/superkaramba/py25_and_admin.patch
@@ -1,6 +1,6 @@
 diff -Naur superkaramba-0.39/admin/acinclude.m4.in superkaramba-0.39-p/admin/acinclude.m4.in
 --- superkaramba-0.39/admin/acinclude.m4.in	2006-02-22 23:39:04.000000000 +0100
-+++ superkaramba-0.39-p/admin/acinclude.m4.in	2006-10-16 14:50:05.000000000 +0200
++++ superkaramba-0.39-p/admin/acinclude.m4.in	2006-10-17 23:35:07.000000000 +0200
 @@ -4625,12 +4625,14 @@
  
  AC_DEFUN([KDE_CHECK_PYTHON],
@@ -19,7 +19,7 @@ diff -Naur superkaramba-0.39/admin/acinclude.m4.in superkaramba-0.39-p/admin/aci
       ])
 diff -Naur superkaramba-0.39/admin/cvs.sh superkaramba-0.39-p/admin/cvs.sh
 --- superkaramba-0.39/admin/cvs.sh	2006-03-19 00:14:38.000000000 +0100
-+++ superkaramba-0.39-p/admin/cvs.sh	2006-10-16 14:51:03.000000000 +0200
++++ superkaramba-0.39-p/admin/cvs.sh	2006-10-17 23:35:07.000000000 +0200
 @@ -32,7 +32,7 @@
  required_autoconf_version="2.53 or newer"
  AUTOCONF_VERSION=`$AUTOCONF --version | head -n 1`
@@ -38,3 +38,12 @@ diff -Naur superkaramba-0.39/admin/cvs.sh superkaramba-0.39-p/admin/cvs.sh
    "" )
      echo "*** AUTOHEADER NOT FOUND!."
      echo "*** KDE requires autoheader $required_autoconf_version"
+@@ -68,7 +68,7 @@
+     echo "*** KDE requires automake $required_automake_version"
+     exit 1
+     ;;
+-  automake*1.6.* | automake*1.7* | automake*1.8* | automake*1.9*)
++  automake*1.6.* | automake*1.7* | automake*1.8* | automake*1.9* | automake*1.10* )
+     echo "*** $AUTOMAKE_STRING found."
+     UNSERMAKE=no
+     ;;
