pacman-tools-1.3.4-17-x86_64
* update git patch for repoman custom ssh port support

diff --git a/source/devel/pacman-tools/git.patch b/source/devel/pacman-tools/git.patch
--- a/source/devel/pacman-tools/git.patch
+++ b/source/devel/pacman-tools/git.patch
@@ -39,10 +39,44 @@ index f2458dc..38765b0 100644
  dist:
  	git archive --format=tar --prefix=pacman-tools-$(VERSION)/ HEAD > pacman-tools-$(VERSION).tar
 diff --git a/bumppkg b/bumppkg
-index fe4226b..0899586 100755
+index fe4226b..ac1496e 100755
 --- a/bumppkg
 +++ b/bumppkg
-@@ -60,11 +60,11 @@ get_root()
+@@ -1,22 +1,22 @@
+ #!/bin/bash
+-# 
++#
+ #   bumppkg
+-#  
++#
+ #   Copyright (c) 2006-2007 by Miklos Vajna <vmiklos@frugalware.org>
+-#  
++#
+ #   This program is free software; you can redistribute it and/or modify
+ #   it under the terms of the GNU General Public License as published by
+ #   the Free Software Foundation; either version 2 of the License, or
+ #   (at your option) any later version.
+-# 
++#
+ #   This program is distributed in the hope that it will be useful,
+ #   but WITHOUT ANY WARRANTY; without even the implied warranty of
+ #   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ #   GNU General Public License for more details.
+-#  
++#
+ #   You should have received a copy of the GNU General Public License
+ #   along with this program; if not, write to the Free Software
+-#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
++#   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,
+ #   USA.
+ #
+ 
+@@ -56,15 +56,15 @@ get_root()
+ 	echo $i
+ 	fi
+ }
+-
++USE_COLOR=y
  src_cleanup()
  {
  	Fmessage "cleaning up old source files"
@@ -65,6 +99,47 @@ index fe4226b..0899586 100755
  	if [[ "$newpkgver" =~ " " ]] || [ -z "$newpkgver" ]; then
  		die "Dunno what is the new version or this package is already up to date!"
  	fi
+@@ -127,9 +127,9 @@ do_push()
+ 	fi
+ }
+ 
+-USE_COLOR="y"
++
+ . /usr/lib/frugalware/fwmakepkg
+-. /etc/makepkg.conf
++. /etc/repoman.conf
+ 
+ if [ "$1" == "-h" -o "$1" == "--help" ]; then
+ 	man bumppkg
+@@ -152,11 +152,6 @@ if [ "$1" == "--rebuild" ]; then
+ 	source ./FrugalBuild || die "failed to source the FrugalBuild!"
+ 	newrel=$(echo $pkgrel|sed 's/[0-9]\+$//')$(($(echo $pkgrel|sed 's/.*[^0-9]\([0-9]\+\)$/\1/')+1))
+ 	update_pkgrel $newrel
+-	if [ "$tree" == "stable" ] && echo "$pkgrel" | grep -q "^[0-9]\+$"; then
+-		# first stable rebuild, like 1 -> 2foo1
+-		codename=$(sed 's/.*(\(.*\))/\1/' /etc/frugalware-release|tr '[A-Z]' '[a-z]')
+-		update_pkgrel ${newrel}${codename}1
+-	fi
+ 	if [ "$1" != "--nobuild" ]; then
+ 		do_build $tree u
+ 	else
+@@ -172,6 +167,16 @@ if [ "$1" == "--rebuild" ]; then
+ 	exit 0
+ fi
+ 
++
++if [ "$1" = "--update" ]; then
++
++	source ./FrugalBuild || die "failed to source the FrugalBuild!"
++	newrel=$(echo $pkgrel|sed 's/[0-9]\+$//')$(($(echo $pkgrel|sed 's/.*[^0-9]\([0-9]\+\)$/\1/')+1))
++	Fmessage "Updating \$pkgrel from: $pkgrel to $newrel."
++	update_pkgrel $newrel
++	exit 0
++fi
++
+ check_complex
+ update_pkgver
+ update_pkgrel
 diff --git a/chkdep b/chkdep
 index e1e6047..309a9b6 100755
 --- a/chkdep
@@ -390,7 +465,7 @@ index c4bf90f..bcdbbfe 100755
  
  def rollback(argv):
 diff --git a/fblint b/fblint
-index 44bd36d..3a9157c 100755
+index 44bd36d..8c661ed 100755
 --- a/fblint
 +++ b/fblint
 @@ -1,22 +1,22 @@
@@ -453,7 +528,7 @@ index 44bd36d..3a9157c 100755
  check "empty option" "[ -z \"$option\" ]"
  check "valid first group" "! echo $groups |grep -q -- - || echo $groups|grep -q -- -extra$"
 -check "valid options()" "[ -z \"$(echo ${options[@]}|tr ' ' '\n' |grep -v '\(nodocs\|nostrip\|force\|nobuild\|nofakeroot\|scriptlet\|stick\|nomirror\|noversrc\|noccache\|asneeded\|noasneeded\)')\" ]"
-+check "valid options()" "[ -z \"$(echo ${options[@]}|tr ' ' '\n' |grep -v '\(ldlld\|ldbfd\|ldgold\|ldefs\|nowfsecurity\|noclash\|ldlld\|ldbfd\|ofaster\|ofast\|omedium\|osmall\|odebug\|nodevel\|nolto\|nopie\|plt\|nonow\|noprotector\|norelro\|nofortify\|libtool\|static\|nodocs\|nostrip\|force\|nobuild\|nofakeroot\|scriptlet\|stick\|nomirror\|noversrc\|noccache\|asneeded\|noasneeded\)')\" ]"
++check "valid options()" "[ -z \"$(echo ${options[@]}|tr ' ' '\n' |grep -v '\(clang\|ldlld\|ldbfd\|ldgold\|ldefs\|nowfsecurity\|noclash\|ldlld\|ldbfd\|ofaster\|ofast\|omedium\|osmall\|odebug\|nodevel\|nolto\|nopie\|plt\|nonow\|noprotector\|norelro\|nofortify\|libtool\|static\|nodocs\|nostrip\|force\|nobuild\|nofakeroot\|scriptlet\|stick\|nomirror\|noversrc\|noccache\|asneeded\|noasneeded\)')\" ]"
  check "archs" "[ ! -z \"$archs\" ]"
  check "up2date" "test -n \"`echo $up2date|sed 's/\$(/\\\\\$(/g'`\""
  _fblint_have_remote_source=n
@@ -744,7 +819,7 @@ index 23c1660..0000000
 ---silentpush::
 -	Just modify the buildscript and let syncpkgd build the binary package.
 diff --git a/repoman b/repoman
-index 76f9dff..fd6c795 100755
+index 76f9dff..a9dbf22 100755
 --- a/repoman
 +++ b/repoman
 @@ -1,22 +1,22 @@
@@ -775,7 +850,18 @@ index 76f9dff..fd6c795 100755
  #   USA.
  #
  
-@@ -403,6 +403,25 @@ upload()
+@@ -344,7 +344,9 @@ server()
+ 
+ _ssh()
+ {
+-	$repoman_ssh $host "$sudo_cmd repoman server $*"
++	
++	[[ -z "$repoman_port" ]] && repoman_port="22"
++	$repoman_ssh -p$repoman_port $host "$sudo_cmd repoman server $*"
+ }
+ 
+ delete()
+@@ -403,24 +405,32 @@ upload()
  			echo "Please fix your package."
  			exit 1
  		fi
@@ -801,7 +887,28 @@ index 76f9dff..fd6c795 100755
  		name=`basename $src`
  		msg "Requesting a temporary file"
  		tmp=`_ssh "mktemp"`
-@@ -601,9 +620,15 @@ $@" | darcs rec -a --pipe .
+ 		[ -z "$tmp" ] && exit 1
+-		if [  "$REPOMAN_USE_TUNNEL" == "yes" ]; then
+-			## Fix me ? well since we use something like:
+-			## local -> genesis ( genesis acts like tunnel for itself )
+-			## or remote_box -> genesis , local -> remote_box we are always
+-			## using 127.0.0.1 .. scp -S really sucks and I get a lot problems
+-			## with rsync -e with all this tunneling =)
+-			## the other solution may be to force host when tunnel is used to be user@127.0.0.1
+-			## since -p <port> user@local gives out user@genesis .. 
+-			msg "Uploading file: $src (to $tmp) over local tunnel."
+-                        $repoman_scp $src 127.0.0.1:$tmp
+-                else
+-			msg "Uploading file: $src (to $tmp)"
+-                        $repoman_scp $src $host:$tmp
+-                fi
++		msg "Uploading file: $src (to $tmp)"
++		[[ -z "$repoman_port" ]] && repoman_port="22"
++        $repoman_scp -P$repoman_port $src $host:$tmp
+ 		sha=`sha1sum $src|sed 's/\(.*\)  .*/\1/'`
+ 		if ! _ssh "upload '$path' '$tmp' '$sha' '$dest/$src'"; then
+ 			return 1
+@@ -601,9 +611,15 @@ $@" | darcs rec -a --pipe .
  __pkg_commit_info()
  {
  	local commitmsg
@@ -820,7 +927,7 @@ index 76f9dff..fd6c795 100755
  }
  
  commit_info()
-@@ -952,14 +977,20 @@ search()
+@@ -952,14 +968,20 @@ search()
  info()
  {
  	chk_updated $fst_root
@@ -844,7 +951,7 @@ index 76f9dff..fd6c795 100755
  			echo "Repository        : $i"
  			echo "Name              : $pkgname"
  			echo "Version           : $pkgver-$pkgrel"
-@@ -1022,6 +1053,7 @@ upgrade()
+@@ -1022,6 +1044,7 @@ upgrade()
  
  merge()
  {
@@ -852,7 +959,7 @@ index 76f9dff..fd6c795 100755
  	local i repo target
  	if echo $1 |grep -q /; then
  		repo=${1%/*}
-@@ -1030,24 +1062,24 @@ merge()
+@@ -1030,24 +1053,24 @@ merge()
  		repo="${repos[@]}"
  		target=$1
  	fi
@@ -895,7 +1002,7 @@ index 76f9dff..fd6c795 100755
  	found=0
  	for i in ${repo[@]}
  	do
-@@ -1085,11 +1117,8 @@ fi
+@@ -1085,11 +1108,8 @@ fi
  # Initializing variables.
  version='0.3.1'
  if [ -z "$arch" ]; then
@@ -908,6 +1015,56 @@ index 76f9dff..fd6c795 100755
  fi
  mktemp_local="mktemp -p $HOME"
  sudo_env="sudo -E"
+diff --git a/repoman.conf b/repoman.conf
+index b6240c9..090c161 100644
+--- a/repoman.conf
++++ b/repoman.conf
+@@ -8,7 +8,7 @@
+ # the order is important, the first repo will be used as a default for
+ # developer actions (like up, del and so on)
+ source /etc/repoman.d/current
+-#source /etc/repoman.d/stable
++
+ 
+ # default repo to search the include dir in
+ fst_root=/var/fst/
+@@ -26,13 +26,12 @@ upgrade_ignore=""
+ # DEFAULTS:
+ # repoman_ssh="ssh"
+ # repoman_scp="scp"
+-# REPOMAN_USE_TUNNEL="no"
++# repoman_port="22"
+ # See README.Frugalware on HowTo use these
+ 
+-REPOMAN_USE_TUNNEL="no"
+ repoman_ssh="ssh"
+ repoman_scp="scp"
+-
++repoman_port="22"
+ # User configuration
+ if [ -e ~/.repoman.conf ]; then
+ 	source ~/.repoman.conf
+diff --git a/repoman.d/current b/repoman.d/current
+index 9993f51..6858c49 100644
+--- a/repoman.d/current
++++ b/repoman.d/current
+@@ -6,16 +6,8 @@ repos=(${repos[@]} 'current')
+ 
+ current_servers=(
+ "git://github.com/frugalware/frugalware-current.git"
+-"git://gitorious.org/frugalware/frugalware-current.git"
+-"git://git.utsl.gen.nz/mirror/repo.or.cz/frugalware-current.git"
+-"git://repo.or.cz/frugalware-current.git"
+ )
+ 
+-# additional servers in case you are behind a firewall where only http
+-# is allowed:
+-# http://git.gitorious.org/frugalware/frugalware-current.git
+-# http://git.utsl.gen.nz/mirror/repo.or.cz/frugalware-current.git
+-# http://repo.or.cz/r/frugalware-current.git
+ 
+ # the rest is only for developers who upload packages
+ # if the server requires sudo usage, the name of the user to execute the commands as
 diff --git a/repoman.txt b/repoman.txt
 index 5adb852..61e5cb4 100644
 --- a/repoman.txt
