testsuite/srcjunk: apply the new rules

diff --git a/testsuite/srcjunk b/testsuite/srcjunk
--- a/testsuite/srcjunk
+++ b/testsuite/srcjunk
@@ -1,8 +1,7 @@
 #!/bin/bash
 
-if [ "$#" -lt 1 ]; then
+if [ "$1" == "--help" ]; then
 	echo "searches for old source files"
-	echo "usage: $0 [--remove] <startdir>"
 	exit 1
 fi
 
@@ -16,7 +15,7 @@ if [ "$1" == "--remove" ]; then
 	remove="y"
 	shift
 fi
-sdir=$1
+sdir=..
 
 newsrcs=`mktemp`
 darcssrcs=`mktemp`
@@ -37,9 +36,9 @@ do
 		do
 			CARCH=$j
 			unset source signatures
-			for i in `set|grep ^_F_|sed 's/=.*//'`; do unset $i; done
+			for k in `set|grep ^_F_|sed 's/=.*//'`; do unset $k; done
 			startdir=`pwd`
-			. FrugalBuild || echo "errors parsing the FrugalBuild for $j"
+			. FrugalBuild || echo "errors parsing the FrugalBuild for $pkgname"
 			for k in "${source[@]}" "${signatures[@]}"
 			do
 				echo "`pwd|sed \"s|$CWD/||\"`/`strip_url $k`" >>$newsrcs
