t: fixes for bash4

diff --git a/t/srcjunk b/t/srcjunk
--- a/t/srcjunk
+++ b/t/srcjunk
@@ -31,7 +31,7 @@ do
 	cd `dirname $i` || continue
 	startdir=`pwd`
 	unset pkgver nobuild options archs
-	. FrugalBuild || echo "errors parsing the FrugalBuild"
+	. ./FrugalBuild || echo "errors parsing the FrugalBuild"
 	if [ ! -z "$pkgname" -a ! "$nobuild" -a ! "`check_option NOBUILD`" ]; then
 		for j in ${archs[@]}
 		do
@@ -39,7 +39,7 @@ do
 			unset pkgver pkgextraver source signatures
 			for k in `set|grep ^_F_|sed 's/\(=.*\| ()\)//'`; do unset $k; done
 			startdir=`pwd`
-			. FrugalBuild || echo "errors parsing the FrugalBuild for $pkgname"
+			. ./FrugalBuild || echo "errors parsing the FrugalBuild for $pkgname"
 			for k in "${source[@]}" "${signatures[@]}"
 			do
 				# skip our own sources
