t: fixes for bash4

diff --git a/t/srcmissing b/t/srcmissing
--- a/t/srcmissing
+++ b/t/srcmissing
@@ -24,7 +24,7 @@ do
 	cd `dirname $i` || continue
 	unset pkgver pkgextraver nobuild options archs
 	export startdir=`pwd`
-	. FrugalBuild || echo "errors parsing the FrugalBuild"
+	. ./FrugalBuild || echo "errors parsing the FrugalBuild"
 	if [ ! -z "$pkgname" -a ! "$nobuild" -a ! "`check_option NOBUILD`" -a ! "`check_option NOMIRROR`" ]; then
 		for j in ${archs[@]}
 		do
@@ -33,7 +33,7 @@ do
 			unset pkgver pkgextraver source
 			for k in `set|grep ^_F_|sed 's/\(=.*\| ()\)//'`; do unset $k; done
 			export startdir=`pwd`
-			. FrugalBuild || echo "errors parsing the FrugalBuild for $j"
+			. ./FrugalBuild || echo "errors parsing the FrugalBuild for $j"
 			for k in "${source[@]}"
 			do
 				[[ "$k" =~ "http://ftp.frugalware.org" ]] && continue
