frugalware-0.4pre2-5-i686 sanility checks for xconfig closes #330

diff --git a/source/base/frugalware/xconfig b/source/base/frugalware/xconfig
--- a/source/base/frugalware/xconfig
+++ b/source/base/frugalware/xconfig
@@ -223,6 +223,18 @@ EOF
 
 ### main
 
+# sanility checks
+
+if [ ! "`type -p xinit`" ]; then
+	echo "Could not find foo, please install it with pacman -S xinit."
+	exit 1
+fi
+
+if [ ! "`type -p xmessage`" ]; then
+	echo "Could not find foo, please install it with pacman -S xmessage."
+	exit 1
+fi
+
 # preparing
 if ! [ -e /dev/zero ]; then
 	nodev=1
