frugalware-0.4rc1-2-i686 xconfig: check for xsetroot

diff --git a/source/base/frugalware/xconfig b/source/base/frugalware/xconfig
--- a/source/base/frugalware/xconfig
+++ b/source/base/frugalware/xconfig
@@ -226,14 +226,21 @@ EOF
 # sanility checks
 
 if [ ! "`type -p xinit`" ]; then
-	echo "Could not find foo, please install it with pacman -S xinit."
-	exit 1
+	echo "Could not find xinit, please install it with pacman -S xinit."
+	ret=1
 fi
 
 if [ ! "`type -p xmessage`" ]; then
-	echo "Could not find foo, please install it with pacman -S xmessage."
-	exit 1
+	echo "Could not find xmessage, please install it with pacman -S xmessage."
+	ret=1
 fi
+
+if [ ! "`type -p xsetroot`" ]; then
+	echo "Could not find xsetroot, please install it with pacman -S xsetroot."
+	ret=1
+fi
+
+[ "$ret" = 1 ] && exit 1
 
 # preparing
 if ! [ -e /dev/zero ]; then
