linux-live-5.5.0-5-i686 use grub instead of isolinux

diff --git a/source/devel-extra/linux-live/linux-live-5.5.0-fwlive.diff b/source/devel-extra/linux-live/linux-live-5.5.0-fwlive.diff
--- a/source/devel-extra/linux-live/linux-live-5.5.0-fwlive.diff
+++ b/source/devel-extra/linux-live/linux-live-5.5.0-fwlive.diff
@@ -1,24 +1,3 @@
-diff -Naur linux-live-5.5.0.orig/cd-root/boot/splash.cfg linux-live-5.5.0/cd-root/boot/splash.cfg
---- linux-live-5.5.0.orig/cd-root/boot/splash.cfg	2005-05-04 20:49:50.000000000 +0200
-+++ linux-live-5.5.0/cd-root/boot/splash.cfg	2006-11-12 16:28:02.000000000 +0100
-@@ -1,3 +1,3 @@
- boot/splash.lss
--0f Welcome to YOUR Live CD. Hit Enter to continue booting or press F1 for help...
-+0f Welcome to FwLive. Hit Enter to continue booting or press F1 for help...
-  
-\ No newline at end of file
-diff -Naur linux-live-5.5.0.orig/cd-root/isolinux.cfg linux-live-5.5.0/cd-root/isolinux.cfg
---- linux-live-5.5.0.orig/cd-root/isolinux.cfg	2006-05-05 22:25:22.000000000 +0200
-+++ linux-live-5.5.0/cd-root/isolinux.cfg	2006-11-12 16:25:56.000000000 +0100
-@@ -7,7 +7,7 @@
- 
- label linux
- kernel boot/vmlinuz
--append vga=769 max_loop=255 initrd=boot/initrd.gz init=linuxrc load_ramdisk=1 prompt_ramdisk=0 ramdisk_size=4444 root=/dev/ram0 rw
-+append vga=788 max_loop=255 initrd=boot/initrd.gz init=linuxrc load_ramdisk=1 prompt_ramdisk=0 ramdisk_size=4444 root=/dev/ram0 rw
- 
- label memtest
- kernel boot/memtest
 diff -Naur linux-live-5.5.0.orig/cd-root/make_disk.sh linux-live-5.5.0/cd-root/make_disk.sh
 --- linux-live-5.5.0.orig/cd-root/make_disk.sh	2006-05-17 18:42:03.000000000 +0200
 +++ linux-live-5.5.0/cd-root/make_disk.sh	2006-11-12 16:30:06.000000000 +0100
@@ -33,8 +12,8 @@ diff -Naur linux-live-5.5.0.orig/cd-root/make_disk.sh linux-live-5.5.0/cd-root/m
  read-write
 diff -Naur linux-live-5.5.0.orig/cd-root/make_iso.bat linux-live-5.5.0/cd-root/make_iso.bat
 --- linux-live-5.5.0.orig/cd-root/make_iso.bat	2006-02-10 17:09:28.000000000 +0100
-+++ linux-live-5.5.0/cd-root/make_iso.bat	2006-11-12 16:29:41.000000000 +0100
-@@ -7,7 +7,7 @@
++++ linux-live-5.5.0/cd-root/make_iso.bat	2006-11-26 01:14:14.000000000 +0100
+@@ -7,12 +7,10 @@
  
  if "%1"=="" goto error1
  
@@ -43,18 +22,60 @@ diff -Naur linux-live-5.5.0.orig/cd-root/make_iso.bat linux-live-5.5.0/cd-root/m
  
  REM  isolinux.bin is changed during the ISO creation,
  REM  so we need to restore it from backup.
+-copy /Y boot\isolinux.bi_ boot\isolinux.bin
+-if not "%errorlevel%"=="0" goto error2
+ 
+ tools\WIN\mkisofs.exe @tools\WIN\config -o "%1" -A "%CDLABEL%" -V "%CDLABEL%" .
+ goto theend
+@@ -22,10 +20,6 @@
+ echo Example: %0 c:\target.iso
+ goto theend
+ 
+-:error2
+-echo Can't recreate isolinux.bin, make sure your current directory is writable!
+-goto theend
+-
+ :theend
+ echo.
+ echo New ISO should be created now.
 diff -Naur linux-live-5.5.0.orig/cd-root/make_iso.sh linux-live-5.5.0/cd-root/make_iso.sh
 --- linux-live-5.5.0.orig/cd-root/make_iso.sh	2006-03-22 22:38:00.000000000 +0100
-+++ linux-live-5.5.0/cd-root/make_iso.sh	2006-11-12 16:29:10.000000000 +0100
++++ linux-live-5.5.0/cd-root/make_iso.sh	2006-11-26 01:11:36.000000000 +0100
 @@ -12,7 +12,7 @@
    exit
  fi
  
 -CDLABEL="SLAX"
-+CDLABEL="FWLive"
++CDLABEL="server-0.2-i686 (Alderaan)"
  ISONAME="$1"
  
  if [ "$ISONAME" = "" ]; then
+@@ -22,14 +22,5 @@
+    if [ "$ISONAME" = "" ]; then ISONAME="$SUGGEST"; fi
+ fi
+ 
+-# isolinux.bin is changed during the ISO creation,
+-# so we need to restore it from backup.
+-cp -f boot/isolinux.bi_ boot/isolinux.bin
+-if [ $? -ne 0 ]; then
+-   echo "Can't recreate isolinux.bin, make sure your current directory is writable!"
+-   exit 1
+-fi
+-
+ mkisofs -o "$ISONAME" -v -J -R -D -A "$CDLABEL" -V "$CDLABEL" \
+--no-emul-boot -boot-info-table -boot-load-size 4 \
+--b boot/isolinux.bin -c boot/isolinux.boot .
++-b boot/grub/stage2_eltorito -no-emul-boot -boot-load-size 4 -boot-info-table .
+diff -Naur linux-live-5.5.0.orig/cd-root/tools/WIN/config linux-live-5.5.0/cd-root/tools/WIN/config
+--- linux-live-5.5.0.orig/cd-root/tools/WIN/config	2005-12-11 12:41:16.000000000 +0100
++++ linux-live-5.5.0/cd-root/tools/WIN/config	2006-11-26 01:20:15.000000000 +0100
+@@ -5,5 +5,4 @@
+ -no-emul-boot
+ -boot-info-table
+ -boot-load-size 4 
+--b "boot/isolinux.bin"
+--c "boot/isolinux.boot"
++-b "boot/grub/stage2_eltorito"
 diff -Naur linux-live-5.5.0.orig/initrd/cleanup linux-live-5.5.0/initrd/cleanup
 --- linux-live-5.5.0.orig/initrd/cleanup	2006-07-20 20:19:16.000000000 +0200
 +++ linux-live-5.5.0/initrd/cleanup	2006-11-12 19:55:44.000000000 +0100
@@ -152,8 +173,8 @@ diff -Naur linux-live-5.5.0.orig/initrd/linuxrc linux-live-5.5.0/initrd/linuxrc
  
 diff -Naur linux-live-5.5.0.orig/runme.sh linux-live-5.5.0/runme.sh
 --- linux-live-5.5.0.orig/runme.sh	2006-06-25 11:35:50.000000000 +0200
-+++ linux-live-5.5.0/runme.sh	2006-11-12 16:18:02.000000000 +0100
-@@ -20,11 +20,11 @@
++++ linux-live-5.5.0/runme.sh	2006-11-26 01:28:58.000000000 +0100
+@@ -20,11 +20,7 @@
  
  
  # search for kernel
@@ -163,10 +184,6 @@ diff -Naur linux-live-5.5.0.orig/runme.sh linux-live-5.5.0/runme.sh
 -read NEWKERNEL
 -if [ "$NEWKERNEL" != "" ]; then VMLINUZ="$NEWKERNEL"; fi
 +VMLINUZ=$ROOT/boot/vmlinuz-`uname -r`
-+#if [ -L "$VMLINUZ" ]; then VMLINUZ=`readlink -f $VMLINUZ`; fi
-+#echo -ne "Enter path for the kernel you wanna use [hit enter for $VMLINUZ]: "
-+#read NEWKERNEL
-+#if [ "$NEWKERNEL" != "" ]; then VMLINUZ="$NEWKERNEL"; fi
  if [ "`ls $VMLINUZ 2>>$DEBUG`" = "" ]; then echo "cannot find $VMLINUZ"; exit 1; fi
  
  header "Creating LiveCD from your Linux"
