checkpkgs Cosmetics on the output Add a help message

diff --git a/tools/checkpkgs b/tools/checkpkgs
--- a/tools/checkpkgs
+++ b/tools/checkpkgs
@@ -36,23 +36,37 @@ chk_status() # $1 = path to a FrugalBuild script, $2 = repo
 		repo=${group}
 	fi
 	if [[ "${WHICH}" == "a" ]] ; then
-		printf "\033[01m%s\t\033[0m%s\t\033[01;%smi686\t\033[01;%smx86_64\033[0m\n" \
-		${pkg} ${repo} ${status32} ${status64}
+		msg ${pkg} ${repo} ${status32} ${status64}
 	elif [[ "${WHICH}" == "d" ]] && (( ${status32} != ${status64} )) ; then
-		printf "\033[01m%s\t\033[0m%s\t\033[01;%smi686\t\033[01;%smx86_64\033[0m\n" \
-		${pkg} ${repo} ${status32} ${status64}
+		msg ${pkg} ${repo} ${status32} ${status64}
 	elif [[ "${WHICH}" == "m" ]] && (( ${status32} == 31 )) || (( ${status64} == 31 )) ; then
-		printf "\033[01m%s\t\033[0m%s\t\033[01;%smi686\t\033[01;%smx86_64\033[0m\n" \
-		${pkg} ${repo} ${status32} ${status64}
+		msg ${pkg} ${repo} ${status32} ${status64}
 	fi
-#	printf "\\033[01m%s\t\t\t\t\033[01;%smi686\t\033[01;%smx86_64\033[0m\n" \
-#		$pkg $status32 $status64
+}
+
+help_msg()
+{
+	echo "checkpkgs [-a] [-d] [-m]"
+	echo
+	echo "     -a    Print out all packages"
+	echo -e "     -d    Print packages that are not in i686 \033[01mand\033[0m x86_64 or"
+	echo "           not found."
+	echo "     -m    Print only packages that are not found."
+	echo
+}
+
+msg() # $1 = package name, $2 = repo, $3 = status i686, $4 = status x86_64
+{
+	printf "\033[01m%-40s\t\033[0m%s\t\033[01;%smi686\t\033[01;%smx86_64\033[0m\n" \
+	$1 $2 $3 $4
 }
 
 case $1 in
 	--all|-a)     WHICH=a ;;
 	--diff|-d)    WHICH=d ;;
 	--missing|-m) WHICH=m ;;
+	--help|-h)    help_msg && exit 0 ;;
+	*)            help_msg && exit 1 ;;
 esac
 
 cd ../source || exit 1
