tools/dumpabi: revise the script to use the new helper binary

diff --git a/tools/dumpabi b/tools/dumpabi
--- a/tools/dumpabi
+++ b/tools/dumpabi
@@ -5,25 +5,28 @@ if [ -z "$1" ]; then
 	exit 1
 fi
 
-export LC_ALL=C
-DIR="$(mktemp -td)"
-if [ "$1" == "$(basename $1)" ]; then
-	FPM="$(pwd)/$1"
-else
-	FPM="$1"
+FPM="$1"
+
+if [ ! -f "$FPM" ]; then
+	echo "$FPM does not exist."
+	exit 1
 fi
-IFS=$'\n'
 
-cd "$DIR"
+HELPER="$(dirname "$0")/dumpabi-helper"
 
-tar -xf "$FPM"
+if [ ! -f "$HELPER" ]; then
+	echo "Helper binary cannot be found."
+	exit 1
+fi
 
-chmod -R 0777 .
+export LC_ALL=C
 
-for i in $(find . -type f | file -f - | sed -rn 's|([^:]+):.*ELF.*|\1|p'); do
-	for j in $(objdump -p "$i" | sed -rn 's|\s*NEEDED\s*(\S+)\s*|\1|p'); do
-		echo "${i/.\//}: $j"
-	done
-done
+DIR="$(mktemp -td)"
+
+tar -C "$DIR" -x -f "$FPM"
+
+chmod -R 0777 "$DIR"
+
+"$HELPER" "$DIR"
 
 rm -rf "$DIR"
