audit-2.8.1-3-x86_64
* fix removing  kernel cmd stuff..
* however it doesn't make any sense like this..
  we need remove the stuff from grub package too
  and move audit to base

diff --git a/source/apps-extra/audit/audit.install b/source/apps-extra/audit/audit.install
--- a/source/apps-extra/audit/audit.install
+++ b/source/apps-extra/audit/audit.install
@@ -7,11 +7,19 @@ post_install()
 		chmod 0600 etc/audit/rules.d/audit.rules
 
 	fi
-	## Remove audit=0 from grub-cmdline. Won't work without
-	echo "Removing audit=0 from cmdline."
-	/usr/bin/sed -i 's/audit=0//g' /etc/default/grub
-	grub-mkconfig > /boot/grub/grub.cfg
-	echo "Removed audit=0 from kernel cmdline. Please reboot"
+        if grep -q audit /etc/default/grub ; then
+	        ## Remove audit=0 from grub-cmdline. Won't work without
+	        echo "Removing audit=0 from cmdline."
+	        /usr/bin/sed -i 's/audit=0//g' /etc/default/grub
+	        grub-mkconfig > /boot/grub/grub.cfg
+        fi
+        ## now check whatever it worked..
+        if ! grep -q audit /etc/default/grub ; then
+	        echo "Removed audit=0 from kernel cmdline. Please reboot"
+        else
+                echo "Removing audit=0 failed.."
+                echo "Please edit /etc/default/grub and remove manually.."
+        fi
 }
 
 post_upgrade()
