audit-2.8.2-1-x86_64
* Version bump

diff --git a/source/apps-extra/audit/audit.install b/source/apps-extra/audit/audit.install
--- a/source/apps-extra/audit/audit.install
+++ b/source/apps-extra/audit/audit.install
@@ -12,13 +12,13 @@ post_install()
 	        echo "Removing audit=0 from cmdline."
 	        /usr/bin/sed -i 's/audit=0//g' /etc/default/grub
                 /usr/sbin/grub-mkconfig -o /boot/grub/grub.cfg
-        fi
-        ## now check whatever it worked..
-        if ! grep -q audit /etc/default/grub ; then
-	        echo "Removed audit=0 from kernel cmdline. Please reboot"
-        else
-                echo "Removing audit=0 failed.."
-                echo "Please edit /etc/default/grub and remove manually.."
+                ## now check whatever it worked..
+                if ! grep -q audit /etc/default/grub ; then
+	                echo "Removed audit=0 from kernel cmdline. Please reboot"
+                else
+                        echo "Removing audit=0 failed.."
+                        echo "Please edit /etc/default/grub and remove manually.."
+                fi
         fi
 }
 
