kompose-0.5.4-1-i686 * made admin work with automake >=1.10

diff --git a/source/kde-extra/kompose/admin.patch b/source/kde-extra/kompose/admin.patch
--- a/source/kde-extra/kompose/admin.patch
+++ b/source/kde-extra/kompose/admin.patch
@@ -1,6 +1,6 @@
 diff -Naurp kompose-0.5.4/admin/cvs.sh kompose-0.5.4-p/admin/cvs.sh
 --- kompose-0.5.4/admin/cvs.sh	2005-09-13 19:41:39.000000000 +0200
-+++ kompose-0.5.4-p/admin/cvs.sh	2006-11-17 22:41:16.000000000 +0100
++++ kompose-0.5.4-p/admin/cvs.sh	2006-12-23 03:26:10.000000000 +0100
 @@ -32,7 +32,7 @@ check_autotool_versions()
  required_autoconf_version="2.53 or newer"
  AUTOCONF_VERSION=`$AUTOCONF --version | head -n 1`
@@ -19,3 +19,12 @@ diff -Naurp kompose-0.5.4/admin/cvs.sh kompose-0.5.4-p/admin/cvs.sh
    "" )
      echo "*** AUTOHEADER NOT FOUND!."
      echo "*** KDE requires autoheader $required_autoconf_version"
+@@ -68,7 +68,7 @@ case $AUTOMAKE_STRING in
+     echo "*** KDE requires automake $required_automake_version"
+     exit 1
+     ;;
+-  automake*1.6.* | automake*1.7* | automake*1.8* | automake*1.9*)
++  automake*1.6.* | automake*1.7* | automake*1.8* | automake*1.9* | automake*1.10*)
+     echo "*** $AUTOMAKE_STRING found."
+     UNSERMAKE=no
+     ;;
